### ISSUE TITLE
Decktape phantomjs pull changes  work with old rasterize.js files ?

### ISSUE THREAD

**Issue by vineet3011** [astefanutti/decktape#1]
@astefanutti , dose this solution work with old config files or we need  to update it with respect to decktape.js and i don't want to use  dzsilder  thing ( How i escape it ? ) i want only my pdf with working hyperlink and header footer will it possible with decktape.js  if it's possible could  you give me hint or guide me .

**Comment by astefanutti** [comment]
@vineet3011, indeed, you can use the improvements I made at the level of PhantomJS with the existing `rasterize.js` example. I've tested it myself on a couple of pages and that worked fine.

I've pushed these improvements in a forked version of PhantomJS here: https://github.com/astefanutti/phantomjs. These will eventually be merged in PhantomJS.

Let me know if that answers your question.

**Comment by vineet3011** [comment]
@astefanutti  . Thanks !! working fine for me with same file .....
