### ISSUE TITLE
"Page crashed!" error for presentations with large data-background-image

### ISSUE THREAD

**Issue by deki** [astefanutti/decktape#105]
I'm unable to run decktape successful for a presentation. I narrowed it down to a slide which has data-background-image set to the image from https://static.pexels.com/photos/398532/pexels-photo-398532.jpeg. 

Decktape stops with the following error message:
```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Other background images are working properly. What could be the reason?

**Comment by astefanutti** [comment]
I suspect this comes from the size of the image. There have been some issues reported to Puppeteer around large images rendering. Is the page loading (you should have `Loading page finished with status: 200` printed in the console)? Could you try with a downscaled version of the image?

I've been able to export a test RevealJS presentation with that image as slide background but it seems the process is consuming lots of memory and CPU.

**Comment by deki** [comment]
A downscaled version is working.

Where can I find the console messages when running the decktape docker container?

**Comment by astefanutti** [comment]
You should have it already printed, e.g.:

```
docker run astefanutti/decktape http://lab.hakim.se/reveal-js slides.pdf
Loading page http://lab.hakim.se/reveal-js ...

Unable to load resource from URL: https://public.slidesharecdn.com/fonts/fontawesome-webfont.woff2?v=4.3.0?cb=1504132674
Loading page finished with status: 200
Reveal JS DeckTape plugin activated
Printing slide #/10/1   (15/33) ...     
Unable to load resource from URL: https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4
Printing slide #/10/3   (17/33) ...
Page error: DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
Printing slide #/22     (30/33) ...
Unable to load resource from URL: https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm
Printing slide #/25     (33/33) ...
Printed 33 slides
```

**Comment by deki** [comment]
Here is my output:

```
docker run --rm -v `pwd`:/home/user astefanutti/decktape file:///home/user/index.html /home/user/slides.pdf
Loading page file:///home/user/index.html ...
Loading page finished with status: 0
Reveal JS DeckTape plugin activated
Printing slide #/4/2    ( 7/26) ...(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by astefanutti** [comment]
The error is emitted at the following location:
https://github.com/GoogleChrome/puppeteer/blob/64124df62f4e81999fe1a0ab45c6fb9718a0e413/lib/Page.js#L88-L93

So it seems the remote Chrome instance devtool protocol has crashed.

I would suggest to try to isolate the issue without DeckTape nor RevealJS into the picture and report an issue to Puppeteer unless it turns out to be a resource issue on your side.

**Comment by astefanutti** [comment]
I'm inclined to close this as I don't see what could possibly done at DeckTape level and given that we have found a workaround.

**Comment by pkgw** [comment]
In at least one case in which I've been running Decktape inside the Docker container, I discovered that I could prevent the crash by increasing the default shared memory segment size by adding `--shm-size 2G` to the `docker run` command line. [Inspired by this comment](https://github.com/GoogleChrome/puppeteer/issues/1321#issuecomment-342883872).

**Comment by astefanutti** [comment]
@pkgw thanks for the info. I'll consider adding the `--disable-dev-shm-usage` flag as well once DeckTape relies on Chrome 65 as documented in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips.
