### ISSUE TITLE
docker container crashes

### ISSUE THREAD

**Issue by johanngb** [astefanutti/decktape#106]
I run 

docker run astefanutti/decktape http://lab.hakim.se/reveal-js slides.pdf

and get

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Unable to create PDF file, make sure that output file target is available
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am on ubuntu 17.04.  I have tried this on two different computers (both 17.04) and get the same error message.  Happy to provide any other information that might be helpful.

**Comment by deki** [comment]
Take a look at the README, you need to specify where to save the result:
`$ docker run --rm -v `pwd`:/slides astefanutti/decktape http://lab.hakim.se/reveal-js slides.pdf`

**Comment by johanngb** [comment]
Thanks for the quick reply!  I tried that first actually, and got the same error message.  I thought maybe something was going wrong with accessing the host file system, so that's why I tried the "simpler" version (Bottom of readme, under "Alternatively, you can use the docker cp command."). 

Is there any other variant that might make sense to try?

**Comment by deki** [comment]
Ok I see. For me that's working fine.

**Comment by johanngb** [comment]
Interesting.  I have a windows machine.  I will install docker on there and try that out too, and let you know what happens.

**Comment by johanngb** [comment]
I got the same error when I tried it on windows.  (Windows 10, fresh docker install).  Are you using the most recent docker image?  Thanks!

**Comment by deki** [comment]
I'm also using Ubuntu 17.04 and it's working fine. You can also try earlier versions, e.g. 1.0.0 also works for me.

**Comment by astefanutti** [comment]
I've just fixed a permissioning issue with the `/slides` directory.

@johanngb could you please retry with the latest `astefanutti/decktape` image?

**Comment by johanngb** [comment]
Yes, it works now.  Thank you so much!

**Comment by astefanutti** [comment]
Thanks for the feedback. Let me close this then.
