### ISSUE TITLE
Error: Unable to activate the RISE DeckTape plugin

### ISSUE THREAD

**Issue by gtolomei** [astefanutti/decktape#110]
Hi,

I'm having some issues in getting `decktape` generate a pdf version of the RISE slides corresponding to one of my Jupyter notebook.
I've successfully installed decktape via `npm` as per the instructions provided.
Then, I've tried several different commands but sadly none of them work. Among those are the following:
`decktape rise http://localhost:8888/notebooks/{NOTEBOOK_NAME}.ipynb slides.pdf`
`decktape rise http://localhost:8888/notebooks/{NOTEBOOK_NAME}.ipynb#/slide-0-0 slides.pdf`
`decktape rise http://localhost:8888/?token={NOTEBOOK_TOKEN} slides.pdf`
One of the errors that I got is:
`Error: Unable to activate the RISE DeckTape plugin for the address: {URL}`
where `{URL}` is either `http://localhost:8888/notebooks/{NOTEBOOK_NAME}.ipynb` or `http://localhost:8888/notebooks/{NOTEBOOK_NAME}.ipynb#/slide-0-0`.
Would you please help me to fix this issue and figure out what's the exact way to generate pdf from RISE slides?

Many Thanks,
Gabriele

**Comment by astefanutti** [comment]
I've just tried on a locally installed Jupyter / RISE and it works OK:

```
$ node decktape.js rise http://localhost:8888/notebooks/2013-12-03-Crank_Nicolson.ipynb test.pdf
Loading page http://localhost:8888/notebooks/2013-12-03-Crank_Nicolson.ipynb ...
Loading page finished with status: 200
RISE DeckTape plugin activated
Default extension for cell metadata editing loaded.
Raw Cell Format toolbar preset loaded.
Slideshow extension for metadata editing loaded.
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
load_extensions { '0': 'livereveal/main',
  '1': 'nb_conda/main',
  '2': 'nb_anacondacloud/main',
  '3': 'nbpresent/js/nbpresent.min' }
Loading extension: livereveal/main
Loading extension: nb_anacondacloud/main
Loading extension: nbpresent/js/nbpresent.min
API request failed (501): The 'None' kernel is not available. Please pick another suitable kernel instead, or install that kernel.
Session: kernel_dead (null)
API request failed (501): The 'None' kernel is not available. Please pick another suitable kernel instead, or install that kernel.
{ readyState: 4,
  getResponseHeader: {},
  getAllResponseHeaders: {},
  setRequestHeader: {},
  overrideMimeType: {},
  statusCode: {},
  abort: {},
  state: {},
  always: {},
  then: {},
  promise: {},
  pipe: {},
  done: {},
  fail: {},
  progress: {},
  complete: {},
  success: {},
  error: {},
  responseText: '{"short_message": "None not found", "message": "The \'None\' kernel is not available. Please pick another suitable kernel instead, or install that kernel."}',
  responseJSON: 
   { short_message: 'None not found',
     message: 'The \'None\' kernel is not available. Please pick another suitable kernel instead, or install that kernel.' },
  status: 501,
  statusText: 'Not Implemented' }
{ readyState: 4,
  getResponseHeader: {},
  getAllResponseHeaders: {},
  setRequestHeader: {},
  overrideMimeType: {},
  statusCode: {},
  abort: {},
  state: {},
  always: {},
  then: {},
  promise: {},
  pipe: {},
  done: {},
  fail: {},
  progress: {},
  complete: {},
  success: {},
  error: {},
  responseText: '{"short_message": "None not found", "message": "The \'None\' kernel is not available. Please pick another suitable kernel instead, or install that kernel."}',
  responseJSON: 
   { short_message: 'None not found',
     message: 'The \'None\' kernel is not available. Please pick another suitable kernel instead, or install that kernel.' },
  status: 501,
  statusText: 'Not Implemented' }
Loading extension: nb_conda/main

Unable to load resource from URL: about:blank
Loading extension: widgets/notebook/js/extension
loaded widgets
Printing slide #/slide-18-0 ( 19/ ?) ...
Printed 19 slides
```

Could you check that the RISE extension is loaded / active? From the Web client, there should be the _Enter/Exit Live Reveal Slideshow_ button:

<img width="803" alt="screen shot 2017-09-07 at 10 37 02" src="https://user-images.githubusercontent.com/366207/30153932-8f5d8a58-93b8-11e7-94be-5b23db2be3e9.png">

**Comment by gtolomei** [comment]
Hi,

Thanks for the quick reply.
I may miss something here but these are the steps that I took in order to install DeckTape on my laptop and use it to generate pdf from RISE slides:

1) Install DeckTape globally:
`> npm install -g decktape`

2) Launch my Jupyter notebook:
`> jupyter notebook {MY_NOTEBOOK_NAME}.ipynb`

3) Click on the _Enter/Exit Live Reveal Slideshow_ button once the notebook is successfully up and running on my web browser at `http://localhost:8888/notebooks/{MY_NOTEBOOK_NAME}.ipynb`

4) From the same directory where I have launched `jupyter notebook` I issue the following command:
`> decktape rise http://localhost:8888/notebooks/{MY_NOTEBOOK_NAME}.ipynb test.pdf`

But this gives me the same error:
`Error: Unable to activate the RISE DeckTape plugin for the address: http://localhost:8888/notebooks/{MY_NOTEBOOK_NAME}.ipynb`

Now, I see your command is slightly different (i.e., it doesn't seem to need DeckTape to be installed via `npm`), therefore I've tried to do the following:

1) Cloning your repo on my laptop:
`> git clone https://github.com/astefanutti/decktape`

2) Execute the command you suggest:
`> node decktape.js rise http://localhost:8888/notebooks/{MY_NOTEBOOK_NAME}.ipynb test.pdf`

Unfortunately, this gives me back the following error:

throw err;
    ^

Error: Cannot find module 'hummus'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gtolomei/Projects/decktape/decktape.js:7:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

Any thoughts about what might possibly cause this?

Many Thanks,
Gabriele

**Comment by astefanutti** [comment]
> 3. Click on the Enter/Exit Live Reveal Slideshow button once the notebook is successfully up and running on my web browser at `http://localhost:8888/notebooks/{MY_NOTEBOOK_NAME}.ipynb`

You should not be activating the RISE plugin manually. The DeckTape RISE plugin does it for you so that's likely the reason of the error. Could you tried without step 3 and let me know?

**Comment by gtolomei** [comment]
Unfortunately, I'm still getting the same error :(
Is there any way to double-check if the RISE plugin gets correctly activated?
BTW, here is the full error stack:

Loading page http://localhost:8888/notebooks/Lecture_01.ipynb ...
Loading page finished with status: 200
Error: Unable to activate the RISE DeckTape plugin for the address: http://localhost:8888/notebooks/Lecture_01.ipynb
    at createPlugin (/usr/local/lib/node_modules/decktape/decktape.js:220:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Many Thanks,
Gabriele

**Comment by astefanutti** [comment]
It seems the button cannot be found:
https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/rise.js#L15-L18

Could you check that the button id is `start_livereveal`?

If that's the case, then could you try adding a delay, e.g:

    decktape rise http://localhost:8888/notebooks/Lecture_01.ipynb test.pdf --load-pause 30000

Just to make sure the it has loaded as I'm surprise you don't have the Jupyter / RISE logs being printed like `Slideshow extension for metadata editing loaded.`.

**Comment by gtolomei** [comment]
Ok, it seems we have made a progress although we're not quite there yet!
First of all, I can confirm the button id is `start_livereveal`.
After issuing the command as you suggest (i.e., with extended delay), I got the following:

Loading page http://localhost:8888/notebooks/Lecture_01.ipynb ...
Loading page finished with status: 200
RISE DeckTape plugin activated
Error: Evaluation failed: ReferenceError: Reveal is not defined
    at _ (<anonymous>:1:14)
    at <anonymous>:7:8
    at Frame._rawEvaluate (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

The RISE DeckTape plugin seems activated successfully now but apparently there is an issue on Reveal.

Sorry for bothering :(
G.

**Comment by astefanutti** [comment]
No worries.

With the local clone that you have, could you manually increase the delay here:

https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/rise.js#L31

And give it a try. I still wonder why it requires larger delays on your machine. Anyway, that'd be a additional reason to bring deterministic timing / callback to RISE...

**Comment by gtolomei** [comment]
Once I've made the change to the above delay, I'm assuming this means I need to execute the following command (from within the directory where I've cloned decktape):
`> node decktape.js rise http://localhost:8888/notebooks/Lecture_01.ipynb ~/Desktop/test.pdf`
Problem is that with this approach I'm getting this:
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/gtolomei/Projects/decktape/plugins/decktape.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

I guess this is possibly because I've installed decktape globally using `npm`. In fact, if I've tried to increase the delay to 60000 from here:
`/usr/local/lib/node_modules/decktape/plugins/rise.js` and issue the same usual command:

`decktape rise http://localhost:8888/notebooks/Lecture_01.ipynb test.pdf`

Unfortunately, I'm still getting the same error:

**Comment by gtolomei** [comment]
Sorry, I've accidentally pressed "Return"...
I was saying that even if I increase the delay from rise.js I'm still getting the same error:

Loading page http://localhost:8888/notebooks/Lecture_01.ipynb ...
Loading page finished with status: 200
RISE DeckTape plugin activated
Error: Evaluation failed: ReferenceError: Reveal is not defined
    at _ (<anonymous>:1:14)
    at <anonymous>:7:8
    at Frame._rawEvaluate (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by astefanutti** [comment]
There are two delays in the `configure` methods:

https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/rise.js#L20-L40

Could you double check you've increased the second one?

Aside from that, I'm afraid I run out of ideas without being able to reproduce on my side. It may due to a new Jupyter / RISE versions combination...

**Comment by gtolomei** [comment]
So, just to be sure I did what you actually suggest:

1) Open `rise.js` under `/usr/local/lib/node_modules/decktape/plugins/`

2) Increase only the second delay (line 31) to 60000 and save the file

3) Run the following:
`> node decktape.js rise http://localhost:8888/notebooks/Lecture_01.ipynb ~/Desktop/test.pdf --load-pause=20000` # I guess `--load-pause` only affects the first delay which waits for the RISE extension to be loaded, is that correct?

Unfortunately, I'm still getting:
Error: Evaluation failed: ReferenceError: Reveal is not defined
    at _ (<anonymous>:1:14)
    at <anonymous>:7:8
    at Frame._rawEvaluate (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

I totally understand there's not much you can do other than what you have already recommended.
I really appreciate your help here but as you say it may be an issue of Jupyter/RISE.

Thanks a lot,
Gabriele

**Comment by astefanutti** [comment]
OK, I've upgraded to RISE 5.x and I'm able to reproduce 👍 Let me see what has changed...

**Comment by gtolomei** [comment]
Thanks a lot,

That's very kind of you!

**Comment by astefanutti** [comment]
OK, I've managed to understand what's going on. For some reason token based authentication seems required so you have to pass the token printed when you start the notebook, e.g.:

    decktape rise http://localhost:8888/notebooks/Lecture_01.ipynb?token=<TOKEN> test.pdf

I've hit another issue at the end:

https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/rise.js#L57

That's due to RISE 5.x that has changed the presentation structure and that can be fixed by replacing it with the proper Reveal API call:

```
hasNextSlide() {
    return this.page.evaluate(_ => !Reveal.isLastSlide());
  }
```

**Comment by gtolomei** [comment]
Thanks a lot!

It works like a charm! :)

Gabriele

**Comment by astefanutti** [comment]
> Thanks a lot!

If you feel generous, you can give the project a star 😉 

> It works like a charm! :)

Out of curiosity for further compatibility, did you have to change the following line:

https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/rise.js#L57

**Comment by gtolomei** [comment]
Star just given ;)

To be honest, I follow your instruction and change the line without even trying to keep it as it is. I can give it a try if you want...

**Comment by astefanutti** [comment]
> To be honest, I follow your instruction and change the line without even trying to keep it as it is. I can give it a try if you want...

No worries, that was just out of curiosity. The change is to be made anyway...

**Comment by gtolomei** [comment]
In fact, I've tried using the previous statement and I do get the following error right before the end of pdf transformation:
...
Printing slide #/slide-5-0 (6/7) ...Error: Evaluation failed: TypeError: Cannot read property 'nodeName' of null
    at _ (<anonymous>:2:61)
    at <anonymous>:2:89
    at Frame._rawEvaluate (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by astefanutti** [comment]
Ok, thanks a lot for the feedback. That confirms my tests. I'll work on improving the RISE plugin based on your feedback.

**Comment by gtolomei** [comment]
No worries! Thank you, indeed!
Yours is really a great tool for generating nice-looking PDFs from notebook slides, which can therefore be easily printed out ;)

**Comment by gtolomei** [comment]
Hi again!

I've just moved to a new laptop and I had to reinstall from scratch my old environment: andaconda, RISE plugin (5.1.0) and, of course, decktape (2.5.0).
Installation went ok but when I'm trying to transform Jupyter notebook in pdf slides using decktype with RISE I'm getting the same old error, i.e., Error: Unable to activate the RISE DeckTape plugin for the address: <URL>
My previous working setting was:
- RISE 5.0.0
- decktape 2.4.3
I've verified the rise.js plugin is exactly the same I had before but inspecting HTML elements on the Jupyter Notebook I have realized that the button id for RISE changed from "start_livereveal" to "RISE", as shown below:

<img width="899" alt="screen shot 2017-11-17 at 12 00 09" src="https://user-images.githubusercontent.com/9001735/32944185-ed67a4e0-cb8e-11e7-8796-a2bd6cab6c45.png">

As such, I thought the issue could be solved just by replacing rise.js with the correct button id. Unfortunately, this solution doesn't solve the problem or, at least, this wasn't enough. Do you have any other clue on how this could be possibly fixed?

Many Thanks

**Comment by gtolomei** [comment]
Never mind!
I was just typing the incorrect URL as input to decktape rise.
So, the fix that I propose (i.e., replacing "start_livereveal" with "RISE" in the rise.js file) actually make decktape 2.5.0 and RISE 5.1.0 work nicely.
Hope this helps!

Thanks,
Gabriele

**Comment by damianavila** [comment]
@astefanutti This is still happening, but I think there is another issue because changing the plugin from "start_livereveal" to "RISE" is not enough to make it work. I followed these steps:

1. Install: `npm install decktape`

2. Check version: 
```
`npm bin`/decktape version
2.8.7
```

3. Modify the plugin in place to change from "live_reveal" into "RISE"

4. Start the notebook server, copy the url with the token and run the whole thing:

```
`npm bin`/decktape rise http://127.0.0.1:8888/notebooks/examples/README.ipynb?token=ce0db9e3e07353d5c898948744627a5f269df8e7aceebef3 /Users/davila/Downloads/README.pdf
```

It only print one slide and it is just the notebook view (not the slideshow one). Can you take a look and see if you can reproduce it?

**Comment by astefanutti** [comment]
@damianavila I've just pushed 1880d00e7bb630aa40f8bc9736403a9667a1574c that should solve the compatibility issue with RISE 5.1+ (#131). With that change, I've been able to successfully export notebooks with RISE.

Could you please give that change a try? I'm holding a new release for a while until I get your confirmation.

**Comment by astefanutti** [comment]
```console
$ conda list
 Name                  Version             Build     Channel
 rise                  5.3.0               py35_0    damianavila82
```

In your case it seems the RISE plugin from DeckTape does not activate, and falls back to the generic plugin. You can use `decktape rise <URL> <file> to deactivate the fallback. That'll simplify troubleshooting. That being said, with the latest changes, I don't see why the RISE plugin would not activate.

**Comment by damianavila** [comment]
This is the output I get:

```
$ `npm bin`/decktape rise http://127.0.0.1:8888/notebooks/examples/README.ipynb?token=a457fde0bc3f5d74d26a967e83ef4617eb53d3434aed025d /Users/davila/Downloads/README.pdf
Loading page http://127.0.0.1:8888/notebooks/examples/README.ipynb?token=a457fde0bc3f5d74d26a967e83ef4617eb53d3434aed025d ...
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
load_extensions JSHandle@array
Loaded moment locale en
Loading extension: nbextensions_configurator/config_menu/main
Loading extension: rise/main
Session: kernel_created (91a440a2-ee6d-4db3-a344-541b92f26037)
Starting WebSockets: ws://127.0.0.1:8888/api/kernels/b51958ce-c4f4-43e5-9b11-5595dc627ca6
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
Reveal initialized
Kernel: kernel_connected (b51958ce-c4f4-43e5-9b11-5595dc627ca6)
Kernel: kernel_ready (b51958ce-c4f4-43e5-9b11-5595dc627ca6)
Loading page finished with status: 200
RISE plugin activated
Printing slide #/slide-0-0 (  1/ ?) ...
Printed 1 slides
```

The plugin seems activated...
> You can use `decktape rise to deactivate the fallback

I did not understood what I have to do to deactivate the fallback.

**Comment by astefanutti** [comment]
Ok, that seems to work. I guess you've checked, but are you sure README.ipynb contains slides? Would you be able to upload it here so that I can give it a try?

**Comment by astefanutti** [comment]
My output:
```console
$ node decktape.js http://localhost:8888/notebooks/README.ipynb?token=f46b01170a0232848cfa610b8db5874fcf8df7640c3031a4 test.pdf
Loading page http://localhost:8888/notebooks/README.ipynb?token=f46b01170a0232848cfa610b8db5874fcf8df7640c3031a4 ...
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
load_extensions JSHandle@array
Loaded moment locale en
Kernelspec not found: JSHandle@object
Failed to load resource: the server responded with a status of 404 (Not Found)
Loading extension: nbpresent/js/nbpresent.min
Failed to load extension: JSHandle@array JSHandle@error
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Loading extension: rise/main
Loading extension: nb_anacondacloud/main
Failed to load resource: the server responded with a status of 404 (Not Found)
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Loading extension: nb_conda/main
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/slide-7-0 (9/9) ...
Printed 9 slides
```
And the PDF: [test.pdf](https://github.com/astefanutti/decktape/files/2310471/test.pdf)

The plugin doesn't do much and relies on the Reveal API to instrument the presentation. I wonder what can go wrong...

**Comment by damianavila** [comment]
OK... the problem was I was using `desktape rise`, removing `rise` from that command allows the Reveal.js plugin being activated (`Reveal JS plugin activated in your output`) and things work. I would expect `desktape rise` to work as well... what am I missing?

**Comment by astefanutti** [comment]
Hum, it should work equally between `decktape rise <URL> ...` and decktape <URL>...`. Actually I've been able to reproduce your issue with your example notebook. I suspect there is a timing issue between the button click event and waiting Reveal has loaded. Let me come back to you on this.

**Comment by damianavila** [comment]
OK, thanks for taking a look!!

**Comment by astefanutti** [comment]
I think It's a side effect of the `autolaunch` option. As the DeckTape RISE plugin always clicks the RISE button irrespective of the `autolaunch` option value, it closes the slideshow, when it's set to true. I still need to find the best approach to detect RISE is already in slideshow mode and review the init condition as well...

**Comment by damianavila** [comment]
Oh... that could be the issue....

> I still need to find the best approach to detect RISE is already in slideshow mode and review the init condition as well...

Maybe you can look for this tag to know if you are (or not) in the slideshow view:
https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L1006

**Comment by damianavila** [comment]
Just confirming that putting `autoLaunch` as `false` in the slideshow allowed me to print the slides as expected with `decktape rise...` command.

**Comment by astefanutti** [comment]
Thanks for the suggestion and confirmation. I've just pushed some changes that takes your suggestion into account. Would you be able to give it a try to confirm it works for you?

**Comment by damianavila** [comment]
Do you have a commit ref for the changes? So I can do the changes in place (I have not installed decktape in dev mode ;-).

**Comment by astefanutti** [comment]
You should take f0ff905989c4a37af25bab0920fb820f98579911 and b79d28a657582f20b11335185cf70f2f48fe9a6a.

**Comment by damianavila** [comment]
OK, will test as soon as possible and report back.
