### ISSUE TITLE
Trying to build custom Docker Container Failure

### ISSUE THREAD

**Issue by Blackbms** [astefanutti/decktape#113]
Due to network issues I need to build my own custom docker image so that I can set my proxy servers.  When I attempt to build the image I fail wen running 
```> puppeteer@0.10.2 install /decktape/node_modules/puppeteer```
with the following message:
```
ERROR: Failed to download Chromium r497674! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
npm info lifecycle puppeteer@0.10.2~install: Failed to exec install script
npm WARN decktape@2.3.0 No license field.
```

Any assistance would be most helpful

**Comment by astefanutti** [comment]
Ah that's Puppeteer trying to download Chrome at install. You can set some environment variables as documented in  https://github.com/GoogleChrome/puppeteer/blob/45f264024b16ee0a23e8d5d9a974720108180997/docs/api.md#environment-variables.

Let me know if that works for you.

**Comment by Blackbms** [comment]
I have already set those in the Dockerfile and the rest of the install works just fine.  
I have even set `npm config set proxy <proxy server>`

Here is the rest of the error message:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by astefanutti** [comment]
I think that comes from https://github.com/GoogleChrome/puppeteer/commit/b8bb80a0892a9a940e699d44b4269417ace50da9 which is included in Puppeteer `0.11.0`. Could you try upgrading Puppeteer (maybe via DeckTape)?

**Comment by Blackbms** [comment]
Ok, I have checkout DeckTape 2.4.0 out and still have the same problem.
It appears that we are trying to use puppeteer version 0.11.0 which is the latest released a few days ago.
Based on the pull request in Github and description of that issue I would have thought this might have fixed it.

**Comment by astefanutti** [comment]
Hum, that should definitely works :( Maybe that something to do with Docker.

Either do:

     ENV http_proxy <proxy_url>
     ENV https_proxy <proxy_url>

Or try:

    $ docker run --env http_proxy=<proxy_url> ...

Could you share your Dockerfile?

**Comment by Blackbms** [comment]
```
FROM node:8.4.0-slim

ENV NODE_ENV production
ENV TERM xterm-color
ENV HTTP_PROXY http://proxyvipecc.nb.ford.com:83/
ENV HTTPS_PROXY https://proxyvipecc.nb.ford.com:83/
ENV http_proxy http://proxyvipecc.nb.ford.com:83/
ENV https_proxy https://proxyvipecc.nb.ford.com:83/

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
    libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
    libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
    libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
    libnss3

WORKDIR /decktape

COPY package.json ./
COPY libs libs/
COPY plugins plugins/
COPY decktape.js ./

RUN chown -R node:node /decktape

# https://github.com/moby/moby/issues/20295
RUN mkdir /slides
RUN chown -R node:node /slides

USER node

RUN npm config set proxy http://proxyvipecc.nb.ford.com:83/
RUN npm config set https-proxy https://proxyvipecc.nb.ford.com:83/

RUN npm install

WORKDIR /slides

# The --no-sandbox option is required for the moment
# https://github.com/GoogleChrome/puppeteer/issues/290
ENTRYPOINT ["node", "/decktape/decktape.js", "--no-sandbox"]

CMD ["-h"]
```

**Comment by Blackbms** [comment]
Your idea of putting the -env on the command line worked.  Thanks.  :+1:

**Comment by Blackbms** [comment]
I'm going to close this as you were able to answer my questions.  Thanks again.
