### ISSUE TITLE
decktape hangs at audio tag

### ISSUE THREAD

**Issue by jonathanlilly** [astefanutti/decktape#115]
Hi, 

Using decktape with remark:

    $ decktape remark http://www.jmlilly.net/talks/oslo/v2/lookatthedata.html lookatthedata.pdf

I got errors like this:

    Unable to load resource from URL: http://www.jmlilly.net/talks/videos/weddellseal.wav

After which, decktape would hang and then timeout.  I tracked this down to audio tags like this:

```
<audio controls
source src="../../videos/weddellseal.wav" type="audio/ogg"
</audio>
```

Commenting out the audio tags solved the problem.

**Comment by astefanutti** [comment]
Thanks for the report. It turns out the presentation contains some large audio files that Chrome responds with 206 Partial content, and the `load` event is never dispatched.

I've improved the wait condition in a9ef2120ef66c5d5c267090ee9003559b5c38341 that solves the issue so you can give it a try. Feel free to reopen if you face any other issue.

**Comment by jonathanlilly** [comment]
Thanks so much, Antonin! It works fine now.
I also have a nomination for you for your example gallery. I have a set of very detailed online course notes for time series analysis that is generated using remark.js. All the pdfs for the chapters are made with decktape, probably a few hundred pages altogether.
If this is of interest the best link is probably to the table of contents, from which all the pdfs can be accessed. You could just call it “Time Series Analysis Course Notes” or something like that.
http://jmlilly.net/talks/oslo/v2/index.html#2 [http://jmlilly.net/talks/oslo/v2/index.html#2]

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.63&pv=10.12.6&source=email_footer_2]
On Fri, Sep 29, 2017 at 7:03 AM, Antonin Stefanutti <notifications@github.com> wrote:
Thanks for the report. It turns out the presentation contains some large audio files that Chrome responds with 206 Partial content, and the load event is never dispatched.

I've improved the wait condition in a9ef212 [https://github.com/astefanutti/decktape/commit/a9ef2120ef66c5d5c267090ee9003559b5c38341] that solves the issue so you can give it a try. Feel free to reopen if you face any other issue.

**Comment by astefanutti** [comment]
> Thanks so much, Antonin! It works fine now.

Great! If you feel generous you can give the project a star, it's always appreciated 😉.

> I also have a nomination for you for your example gallery. I have a set of very detailed online course notes for time series analysis that is generated using remark.js. All the pdfs for the chapters are made with decktape, probably a few hundred pages altogether.
If this is of interest the best link is probably to the table of contents, from which all the pdfs can be accessed. You could just call it “Time Series Analysis Course Notes” or something like that.
[http://jmlilly.net/talks/oslo/v2/index.html#2](http://jmlilly.net/talks/oslo/v2/index.html#2)

It's looks gorgeous! I'll at to the gallery ASAP.
