### ISSUE TITLE
I get an error when trying to run deck tape the first time

### ISSUE THREAD

**Issue by jkohlin** [astefanutti/decktape#119]
I installed it at the Downloads folder and then ran it locally:
`$ npm install decktape 
$ ´npm bin´/decktape`
But I get this:
`node_modules/decktape/decktape.js:162
(async () => {
       ^
SyntaxError: Unexpected token (`

I also tried to install it globally, but instead got an error while installing 
`npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/decktape/decktape.js' -> '/usr/local/bin/decktape'`

I'm probably doing something wrong, but have no idea what that might be

**Comment by astefanutti** [comment]
For the first error, DeckTape requires Node version 7.10.0+ as it uses async / await.

For the second error, it looks like a permission issue. You may try `sudo npm i -g decktape`.

Make sure your NPM version is recent as well.

**Comment by jkohlin** [comment]
Strange, I have Node 7.4:
![Terminal screenshot](https://kohlin.net/images/decktape-error.png)

**Comment by astefanutti** [comment]
Given that DeckTape requires Node version v7.10.0+ and that you have v7.4.0 which is older, it sounds logical. You should be able to fix the error by upgrading Node to a version greater than 7.10.0.

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if upgrading Node is not the solution.
