### ISSUE TITLE
I get an error: Can't find variable: __dirname 

### ISSUE THREAD

**Issue by Nicolabo** [astefanutti/decktape#121]
Hi I try to build pdf slides from remark presentation. I installed phantomjs (2.1.1 version). I got several error:
1. At first I get error:

```
Error: Cannot find module 'nomnom'

  phantomjs://platform/bootstrap.js:299 in require
  phantomjs://platform/bootstrap.js:263 in require
```

So I `npm install nomnom` and execute `phantomjs decktape.js ...` once again. I get another error:

```
Error: Cannot find module 'printer'

  phantomjs://platform/bootstrap.js:299 in require
  phantomjs://platform/bootstrap.js:263 in require
```

So I `npm install printer` and execute `phantomjs decktape.js ...` once again. I get another error:

```
ReferenceError: Can't find variable: __dirname

  phantomjs://platform/printer.js:7
TypeError: undefined is not a constructor (evaluating 'require('printer').create()')

  phantomjs://code/decktape.js:23 in global code
```

Don't know what do to next. Any ideas? I work on MacOS.

**Comment by astefanutti** [comment]
DeckTape has moved to Node / Puppeteer so you should not use PhantomJS anymore. You can find the installation instructions here: https://github.com/astefanutti/decktape#install.

**Comment by Nicolabo** [comment]
Thanks,

**Comment by astefanutti** [comment]
Closing as this seems to work for you now.
