### ISSUE TITLE
Chrome/Puppeteer failed to launch on Ubuntu 14.04

### ISSUE THREAD

**Issue by onetapbeyond** [astefanutti/decktape#126]
When testing decktape 2.6.1 on an Ubuntu 14.04 server (having installed using `npm` as documented in the README) I hit the following problem (stacktrace below):

**chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory**

I tried to install this shared library but that just led me to a similar error about another missing library, etc.

So I'm here to ask: is there a set of known library dependencies beyond those dependencies pulled in by `npm` that need to be installed on a Linux server in order for decktape/chrome/puppeteer to work? Is there an `apt-get` I can use?

Decktape 2.6.1 worked just fine on my laptop running OSX. Is decktape 2.6.1 supported (or expected to run) on an Ubuntu server?

The complete stacktrace is here:

Error: Failed to launch chrome!
/home/decktape/2.6.1/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: **error while loading shared libraries: libXcomposite.so.1: cannot open shared object file**: No such file or directory

    at onClose (/home/decktape/2.6.1/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/home/decktape/2.6.1/node_modules/puppeteer/lib/Launcher.js:200:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by astefanutti** [comment]
This should work. You can find the complete list of dependencies here:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch.

This is basically what's used in DeckTape Dockerfile:
https://github.com/astefanutti/decktape/blob/a8300dffaf136af3e7da78ba7860dfa63f22c81e/Dockerfile#L6-L12

**Comment by onetapbeyond** [comment]
Using the set of `apt-get` installs from your Dockerfile worked perfectly, no more unresolved libraries. Thanks for this quick feedback.

**Comment by Mshanmuganathan** [comment]
@astefanutti  that link seems to be a text file. It cannot be cloned. Help this noob please

**Comment by astefanutti** [comment]
@Mshanmuganathan you have to expand the _Debian (e.g. Ubuntu) Dependencies_ section of the Puppeteer documentation https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch. It may be that the Puppeteer documentation is not up-to-date with Ubuntu 18.04. If so you can contact the Puppeteer team.
