### ISSUE TITLE
64-bit version of Windows PhantomJS binary

### ISSUE THREAD

**Issue by jameysiddiqui** [astefanutti/decktape#128]
Hi, 

I m looking for 64bit Windows Phantom Js library. I tried to buils but ended up in multiple issues.
Please Suggest.

Thanks,
Jamey

**Comment by astefanutti** [comment]
PhantomJS is not maintained anymore. DeckTape 2 has moved to Chrome, so PhantomJS are not necessary anymore. You can have a look a the README for the installation instruction.
