### ISSUE TITLE
No HTML link is generated

### ISSUE THREAD

**Issue by ThomasG77** [astefanutti/decktape#13]
I'm working with shower.js
My OS is Ubuntu 14.04 64bits
I'm trying to render the presentation to PDF
My phantom build is working

I run the following command

     ./phantomjs/bin/phantomjs decktape.js shower http://labs.webgeodatavore.com/presentation-openstreetmap/ output.pdf

I have two issues:

* The first one is identical to #3: On Ubuntu,it rasterizes all the slides content. Using wine with Windows binary help me avoid this issue
* Another one is the fact that no html link can be clicked in the presentation whereas I have some of them in the HTML version

Are you able to reproduce the second issue? How can I help to solve it?

**Comment by astefanutti** [comment]
Unfortunately, the second issue that you face, that is hyperlinks not being rendered as clickable links in the PDF documents, is a consequence of the first one, that is Web fonts text being rendered as outline paths and not embedded / selectable text. A fix similar to https://github.com/astefanutti/phantomjs/commit/d32178f5d1ee36595f4b6332969585b93d03ff08 is required for Linux OS. In the meantime, work-around documented in https://github.com/astefanutti/decktape/issues/3#issuecomment-119162526 may be used.

**Comment by astefanutti** [comment]
Sorry for the late reply. I've just tested it with the latest pre-compiled Ubuntu binary (`phantomjs-linux-ubuntu16-x86-64`) on Ubuntu 14.04 (`ubuntu:14.04` Docker image) and the produced PDF document contains hyperlinks, see: [slides.pdf](https://github.com/astefanutti/decktape/files/404288/slides.pdf).

As for the first issue, #3, there has been some progress as the minimal test case has been identified, [QTBUG-52417](https://bugreports.qt.io/browse/QTBUG-52417), for which a work-around has been proposed, https://github.com/ariya/phantomjs/issues/13997#issuecomment-217982183, and that I'll integrate ASAP.

I'm going to close this issue. Do not hesitate to re-open it if needed.
