### ISSUE TITLE
RISE plugin is not compatible with RISE 5.1+

### ISSUE THREAD

**Issue by abhisheietk** [astefanutti/decktape#131]
RISE 5.2 'Enter/Exit Live Reveal Slideshow' button id is changed to "RISE".

By modifying start_'#livereveal' to '#RISE' solves issue.

**Comment by astefanutti** [comment]
Thanks for the report. I find the breaking change: damianavila/RISE@9e6e5c2bb813b0632b4fcbf1cf2e216ce5bdfcd8.

I wonder whether we could use the Jupyter API for the plugin to be more reliable...

Anyway, if you could create a PR, that'd be great. Otherwise, I'll do the change ASAP.

**Comment by astefanutti** [comment]
It's been fixed with 1880d00e7bb630aa40f8bc9736403a9667a1574c.

**Comment by abhisheietk** [comment]
thanks astefanutti
