### ISSUE TITLE
No code rendering with v2.8.0 (remark.js)

### ISSUE THREAD

**Issue by pat-s** [astefanutti/decktape#133]
[Reprex](https://gist.github.com/pat-s/ee37144253e11e8da9947acf8d08ff65)

Running the linked html file with `decktape` v2.8.0 results in no code output. Version 2.6.1 works fine.

I haven't tested `decktape` versions > 2.6.1. "Save as PDF" in current Chrome stable also results in no code output.

Sorry for the ugly PDF output but its sufficient to function as a reprex :duck:

**Comment by astefanutti** [comment]
Would you mind double checking that your HTML file is complete. At first glance, it looks like the first part is missing.

**Comment by pat-s** [comment]
I stripped it to be minimal to not link to all the CSS stylesheets.. You can apply `decktape` on it and see the difference between v2.6.1 and v2.8.0. The `remark.js` information for `decktape` to apply the respective plugin is at the bottom.

**Comment by pat-s** [comment]
Haven't tried it in the browser, only applied `decktape` on it and it worked. Its sufficient to see the non-rendering code with v2.8.0. So saving the file locally and applying `decktape` on it should work.

Its probably not rendering in the browser because I removed the initial links to all the stylesheets etc.

**Comment by astefanutti** [comment]
Correcting the file by adding the following at the top of your example make it working:

```
</html>
</body>

<textarea id="source">
```

I would suggest you correct your file to make it HTML compliant. It might have worked by chance but I'm afraid Decktape won't be able to render presentations that don't even render in the browser.

**Comment by pat-s** [comment]
Hm, now I can't reproduce the error anymore :thinking: 
That's so strange, I could reproduce it 3 times in a row on 2 machines and now v2.8.0 works (not only on the reprex but also on the actual file). And I double checked that I really use v2.8.0.

I am kind of stunned now. Any idea where such temporary problems might come from?

Anyhow, thanks for your quick reply and your work on decktape :+1:
