### ISSUE TITLE
Missing images from Remark.js slides within absolute layer

### ISSUE THREAD

**Issue by sinedied** [astefanutti/decktape#134]
Hello, I'm coming here to seek some help as I've spent hours trying to fix this.
When trying to print this slide with Decktape (also occurs when trying with Chrome directly):
[cloud-productivity.html.zip](https://github.com/astefanutti/decktape/files/1762254/cloud-productivity.html.zip)
the image on the right is missing.

The image is contained in a `position: absolute` layer which overflows from the slide, but that's wanted to crop the image.

The problem is, whatever CSS I try to use (I've tried a lot of combinations using `page-break-*` and `overflow` properties with no luck) the image is never displayed when printing.

Do you (or anyone) have ideas on how can this be fixed?

Thanks!

**Comment by astefanutti** [comment]
Ah, I've already noticed some issues with images overflow and absolute position. I've reported some issues in the Puppeteer project:

https://github.com/GoogleChrome/puppeteer/issues/created_by/astefanutti

But I'm afraid it concerns Chromium PDF component, hence the absence of feedback from the Puppeteer team. I would advise you vote for these issues, create a new one if needed or report directly in Chromium bug tracker.

Unfortunately I have as well spend some time trying to find some workaround without success, so I'm afraid there is nothing much that can be done on DeckTape side.

**Comment by sinedied** [comment]
Thanks, I've upvoted your issues, if I find some free time I'll also push them to the chromium repo.
Since it's more related to Chrome, I'm closing the issue.

Note: As far as I remember, the 1.0.0 version of Decktape which was not relying on Chrome did not have those issues.

**Comment by astefanutti** [comment]
> Note: As far as I remember, the 1.0.0 version of Decktape which was not relying on Chrome did not have those issues.

It seems indeed specific to the Chrome PDF printer. While it has a lot of improvements compared to the old Qt Webkit engine used by PhantomJS, that issue is annoying.
