### ISSUE TITLE
Output filename case differs from request

### ISSUE THREAD

**Issue by utdrmac** [astefanutti/decktape#135]
Here is the command I used:
```
$ node decktape.js remark ~/Documents/tutorial.html ~/Desktop/my_tutorial.pdf
```

And the resulting filename was `My_Tutorial.pdf`

Why was the case changed?

**Comment by astefanutti** [comment]
I've just tried executing the same command on Mac OS and cannot reproduce. There is no intentional logic that could cause such a behaviour in DeckTape.

What OS do you use?

**Comment by utdrmac** [comment]
macos 10.12.6

```
git clone https://github.com/astefanutti/decktape
npm install
node decktape.js remark ~/Documents/tutorial.html ~/Desktop/my_tutorial.pdf
```

**Comment by astefanutti** [comment]
Strange. Running out of idea, could you try without the `~`, maybe something is messing up the tilde expansion.

**Comment by utdrmac** [comment]
Well, I tried it again with `~` and without to repeat but it did not do it this time. If it does in the future, I'll make sure it's repeatable before opening an issue. Cheers.
