### ISSUE TITLE
ERR_ASSERTION Unknown value for options.waitUntil: networkidle0

### ISSUE THREAD

**Issue by utdrmac** [astefanutti/decktape#138]
I used decktape just the other day on my remarkJS slides and it was just fine. Today, same version, different slides and I'm getting this:

```
$ ./decktape.js version
2.8.0

$ node decktape.js remark ~/Documents/training/whatsnew.html ~/Desktop/whatsnew_20180316.pdf
Loading page file:///Users/foo/Documents/training/whatsnew.html ...

AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle0
```

**Comment by utdrmac** [comment]
Just tried it on the slides that worked the other day and getting same error

**Comment by astefanutti** [comment]
It looks like the Chromium version used is not compatible. `networkidle0` has been introduced part of the upgrade to Puppeteer 1.1.1 so it seems your install hasn't caught the required Chromium version.

I would try reinstalling DeckTape, and make sure Chromium install correctly as part of the Puppeteer install.

**Comment by utdrmac** [comment]
@astefanutti I installed decktape with a simple `git clone` and it worked out of the box a couple days ago on my Mac. Now, it stopped working.

**Comment by astefanutti** [comment]
@utdrmac hum that's weird. Still it's very likely a incompatibility with the Chromium version install. I would trying removing the `node_modules` directory and do an `npm install`.

**Comment by utdrmac** [comment]
```
$ npm install -g decktape
/usr/local/bin/decktape -> /usr/local/lib/node_modules/decktape/decktape.js

> hummus@1.0.83 install /usr/local/lib/node_modules/decktape/node_modules/hummus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.83/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.83 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)
.... (compiling)
```

**Comment by utdrmac** [comment]
How can I downgrade/revert to whatever was working before? I haven't made any changes to Chromium (whatever that is) nor node nor decktape.

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/drmac/Documents/Percona/training/decktape/decktape.js:6:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by astefanutti** [comment]
There must be something that has changed ;) It's hard to tell as it seems specific to your environment, but I think there is an issue with the way you install DeckTape. It seems you clone it and install it.

You just have to `npm install -g decktape` and you don't have to clone it. Then `decktape` should be in your path.

**Comment by utdrmac** [comment]
Ok. I removed the git clone'd dir. Did `npm remove -g decktape` and am running `npm install -g decktape` now. Really wish there were binaries of pdfwriter and hummus for my macos/node versions. This compile stuff shows tons of warnings in the code.

**Comment by astefanutti** [comment]
Indeed. Pre-built binaries aren't yet available for Node 9.x. Hopefully they will be made available soon.

**Comment by utdrmac** [comment]
Looks like working again. I cannot imagine what changed since 2 days ago. Thanks

**Comment by astefanutti** [comment]
Great! Heisenbug ;)
