### ISSUE TITLE
Error printing an reveal-presentation

### ISSUE THREAD

**Issue by opensource21** [astefanutti/decktape#14]
I tried to print an presentation with decktape. At the end I get an error from phantomjs
```
Problemsignatur:
  Problemereignisname:	BEX
  Anwendungsname:	phantomjs.exe
  Anwendungsversion:	2.0.0.0
  Anwendungszeitstempel:	55c375c7
  Fehlermodulname:	nvinit.dll_unloaded
  Fehlermodulversion:	0.0.0.0
  Fehlermodulzeitstempel:	50ef1ca7
  Ausnahmeoffset:	72c7ce59
  Ausnahmecode:	c0000005
  Ausnahmedaten:	00000008
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789
```
The PDF seems complete, but the PDF isn't printable :-(

**Comment by astefanutti** [comment]
When you say the PDF isn't printable, do you mean you cannot open it?

In order to troubleshoot your issue, could you please precise what version of PhantomJS you're using and on what OS? Besides, would you have more logs to share, event the original HTML presentation so that I can give it a try?

**Comment by opensource21** [comment]
It can be opened, but if you try to print it the Acrobat-Reader finish with an error.
The version is downloaded via `curl -L http://astefanutti.github.io/decktape/downloads/phantomjs-msvc2013-win64.exe -o bin\phantomjs.exe`
For the standard reveal.js demo phantom.js crashes with an error too, but the pdf is printable. I will try to strip my presentation down, so that I can share it. At the moment the pictures make it difficult to mail it to you.

**Comment by astefanutti** [comment]
I've tried exporting the standard reveal.js presentation and get the following error message:

```
phantomjs-msvc2013-win64.exe decktape.js http://lab.hakim.se/reveal-js test.pdf
Loading page http://lab.hakim.se/reveal-js ...
Loading page finished with status: success
Reveal JS DeckTape plugin activated
Printing slide #/10/2   (26/33) ...
TypeError: undefined is not a constructor (evaluating 'currentVideo.play()')

  http://lab.hakim.se/reveal-js/js/reveal.js:2616 in updateBackground
  http://lab.hakim.se/reveal-js/js/reveal.js:2154 in slide
  http://lab.hakim.se/reveal-js/js/reveal.js:3645 in navigateDown
  http://lab.hakim.se/reveal-js/js/reveal.js:3692 in navigateNext
  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
Printing slide #/25     (43/33) ...
Printed 43 slides
```

This error message is caused by PhantomJS that does not support the `<video>` tag, as detailed in #4. This is just an error message that does not impact the rendering of the remaining presentation, though `<video>` elements won't be rendered in the PDF documents.

As for the printing issue, I haven't been able to reproduced it. That may be caused to the version of Acrobat Reader you're using. In case that is not the latest version, you may want to give the upgraded version a try. I'll retry once you can share you presentation.

**Comment by opensource21** [comment]
Damn you are right it was a problem of the Acrobat Reader. After creating the example and a reboot of the computer I tried it again and now it works. So it's only the error message I get at the end. It's a windows message, but I can ignore it.
![image](https://cloud.githubusercontent.com/assets/429360/9227972/87a4c5ca-4116-11e5-9d8b-bb766202fa7b.png)

Thanks for your support.
