### ISSUE TITLE
How to apply Angular Project.

### ISSUE THREAD

**Issue by Junnie-Jobs** [astefanutti/decktape#142]
As I know, this **Decktape** app is a command line app. I would like to know if There are examples of using this app with typescipt. It's a great app, so I would like to apply it to my developing website, but it does not seem easy.

**Comment by astefanutti** [comment]
Indeed Decktape is a CLI app. I've seen projects integrating it by spawning a dedicated process to call it. It would be possible to extract Decktape core functionalities as a reusable module. I'm not planning to work on it but I would certainly welcome contribution!

**Comment by astefanutti** [comment]
Let me close this as this answers the question.
