### ISSUE TITLE
Weird description on dockerhub

### ISSUE THREAD

**Issue by olberger** [astefanutti/decktape#143]
The contents of https://hub.docker.com/r/astefanutti/decktape/ is barely unreadable... some markdown conversion issue ?

Hth,

**Comment by astefanutti** [comment]
Unfortunately Docker Hub doesn't support Asciidoc rendering, hence the weird description :( Hopefully Docker Hub will fix sooner or later.

**Comment by astefanutti** [comment]
Corresponding issue: docker/hub-feedback#709. You may want to vote it up!
