### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by akakeronos** [astefanutti/decktape#145]
I tried to install decktape on my computer running windows 10 (sorry:)) and the instructions displayed on the README file did not work.

I finally managed to install it running the following command

```
 npm i -g --production windows-build-tools
 npm install --global node-gyp
 npm install --global node-pre-gyp
 npm i hummus --save
 npm install -g --unsafe-perm decktape
```

In case this helps

Thanks for this great piece of software

**Comment by astefanutti** [comment]
Thanks for the instructions. I'll add these to an FAQ or troubleshooting section.

**Comment by oncletom** [comment]
By looking at the [`hummus.js` repo](https://github.com/galkahana/HummusJS), it looks like that's where the `node-gyp` and `node-pre-gyp` deps are located.

I suspect a clean install of decktape for Windows could evolve to this:

```bash
npm i -g --production windows-build-tools
npm install -g --unsafe-perm decktape
```

I'm unsure why `--unsafe-perm` (aka "runs as root") is necessary. @akakeronos did you install Node on Windows with the official installer?

**Comment by akakeronos** [comment]
Yes I did. I installed the 5.6.0 version

**Comment by astefanutti** [comment]
@oncletom I agree this should be condensed. I may find the time to test it, otherwise I'd be inclined to document your condensed instructions and get feedback.

**Comment by oncletom** [comment]
Okay! I installed a Windows10 VM on macOS (thanks [`iectrl`](https://npmjs.com/iectrl)) to dig this a bit further.

On a fresh Win10 machine, the install step is two-fold.

First, a Powershell in `Run as administrator` to install Visual Studio Build Tools and Python 2.7 :

```bash
npm i -g --production windows-build-tools
```

Then, in a Node prompt or regular Powershell window to install decktape _as usual_:

```
npm i -g decktape
```

Thanks @akakeronos — I've learned about `windows-build-tools` (easiest way to install Node build tools in a Node fashion for Windows) and about the `--unsafe-perm` flag :-)

**Comment by akakeronos** [comment]
Thanks for this great piece of software !

**Comment by astefanutti** [comment]
I've just added these instructions to the FAQ with c062d1f2405ee367d0439c791db6cfc86a7e6c91.

Let me know if you have any comments and thanks again for getting the bottom line.

**Comment by astefanutti** [comment]
> Thanks for this great piece of software !

@akakeronos you may want to ⭐️ the project to show support 😉!

**Comment by akakeronos** [comment]
Will do! ;)
