### ISSUE TITLE
Error: Navigation Timeout Exceeded: 60000ms exceeded (reveal.js presentation on localhost)

### ISSUE THREAD

**Issue by raphaelschroiff** [astefanutti/decktape#148]
I am starting decktape with the following command:
`decktape reveal http://localhost:8000/index.html slides.pdf`

But i get a timeout after 1 minute
```
Loading page http://localhost:8000/index.html ...
Error: Navigation Timeout Exceeded: 60000ms exceeded
```

The presentation is served via http-server (https://www.npmjs.com/package/http-server). I can even see the request from headless Chrome in the logs but decktape still gives me the timeouts.

Some lines of the http-server output:
```
[Wed May 09 2018 16:42:47 GMT+0200 (CEST)] "GET /index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/68.0.3419.0 Safari/537.36"
[Wed May 09 2018 16:42:47 GMT+0200 (CEST)] "GET /css/reveal.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/68.0.3419.0 Safari/537.36"
```

**Comment by astefanutti** [comment]
I've just tried it with Decktape 2.8.3 and haven't been able to reproduce. Could you try with version 2.8.3 and provides more info on your environment?

**Comment by astefanutti** [comment]
With 1a98a5b06b71bbb238f4bcb12f3b8bfffa0d36c0, the wait condition has been changed so it may mitigate timeout issues. Let me close this. Feel free to reopen with additional info.
