### ISSUE TITLE
Problem rendering content with CSS image masks to PDF

### ISSUE THREAD

**Issue by amotl** [astefanutti/decktape#149]
Dear @astefanutti,

first things first: Thank you so much for conceiving and maintaining DeckTape, it really solves us a lot of headaches and provides a robust wrapper around HTML to PDF rendering - so far the best we have worked with throughout the years. Of course, kudos also go to the people of Puppeteer fame, especially @aslushnikov and @JoelEinbinder, not to speak of all the engineers working on WebKit and Chrome themselves.

## Introduction
We are supporting the lovely people of [La Quadrature du Net](https://www.laquadrature.net/) on their [GAFAM poster campaign](https://gafam.info/). Currently, we are working on the first beta release of the [GAFAM poster campaign library](https://library.gafam.info/).

Also, Google engineers reading this will hopefully not take the content personally and be offended in any way. [Don't panic](https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Fih0.redbubble.net%2Fimage.46052927.6069%2Fraf%2C750x1000%2C075%2Ct%2Cdd2121%3A8219e99865.jpg&sp=05cc0ad0da42f8f866bea027d6a478cf) ;].

## Problem
After [introducing CSS image masks](https://github.com/posterkit/posterkit-sandbox/commit/63f72f79) to the [PosterKit rendering engine](https://github.com/posterkit/posterkit-sandbox) for being able to apply color schemes to SVG images at runtime, we came across an issue when rendering the corresponding HTML pages to PDF documents.

We tried to describe the issue as good as possible at [SVG yak shaving #2](https://github.com/posterkit/posterkit-sandbox/issues/2#issuecomment-388431859). You can also find a `decktape` command to reproduce the behavior there, all resources are available on public URLs.

## Call for help
We are aware the root cause is probably in one of the downstream components used in DeckTape, most probably with Chrome itself. May we still humbly ask you to have a look at this?

We really would appreciate any help and we believe you or someone from the DeckTape or Puppeteer communities will have some more intrinsic knowledge about the details involved.

Thanks in advance for your efforts!

**Comment by astefanutti** [comment]
My understanding is that it's been fixed.
