### ISSUE TITLE
Would you help to compile a Linux(Centos) version?

### ISSUE THREAD

**Issue by VinceZK** [astefanutti/decktape#15]
Tested the MAC version, it works perfect. Would you also help to compile a Linux version ?

**Comment by astefanutti** [comment]
I don't have Linux boxes readily available at the moment though I'll be uploading corresponding binaries once I have access to them.

**Comment by gavincarr** [comment]
I've got a working CentOS7 version here if you'd like it posted somewhere.

**Comment by astefanutti** [comment]
@gavincarr definitely!

Would you mind creating a PR into the [`gh-pages`](../tree/gh-pages/) branch to upload it into something like `downloads/phantomjs-linux-centos7-amd64`. Just make sure you've run [UPX](http://upx.sourceforge.net) to compress the binary size.

**Comment by gavincarr** [comment]
@astefanutti Done: https://github.com/astefanutti/decktape/pull/16

**Comment by astefanutti** [comment]
@gavincarr Thanks a lot!

@VinceZK could you please test the uploaded version for Linux CentOS 7 and close that issue if that works OK.

**Comment by VinceZK** [comment]
@astefanutti , I tested in my CentOS6.4 (Sorry I do not have CentOS7 right now), the following error reports:  "error while loading shared libraries: libpng15.so.15: cannot open shared object file: No such file or directory"

I thought some lib is missing. And I found the original CentOS binary is 35MB, while @gavincarr gives the binary with 14MB.

**Comment by gavincarr** [comment]
@VinceZK CentOS6 only comes with libpng12.so.0, so the C7 version won't work for you. I'll try and build a C6 version over the weekend. Are you using 64-bit or 32-bit?

My original binary was around 35MB as well, but running it through UPX dropped it down to 14MB.

**Comment by VinceZK** [comment]
@gavincarr Thanks for the clarifying. My CentOS6 runs on 64-bit machine.

**Comment by gavincarr** [comment]
@astefanutti I've just created a pull request with a CentOS6 x86_64 build of phantomjs, if you could merge when you get a chance.

@VinceZK Could you test this version once it's merged?

Thanks.

**Comment by astefanutti** [comment]
@gavincarr I've just merged it. Thanks a lot!

**Comment by VinceZK** [comment]
@astefanutti I tested CentOS6 x86_64 version, and got some situations. When printing some pages, the size is not right. It doesn't happen in normal phantomjs binary. 
@gavincarr At first, I think it's only the CentOS6 binary. Then I tested MAC binary, the same problem. 

You can find the difference from the 2 attached images. The first is the normal binary, and the second is the desktape bianry. I am sorry the page is in Chinese, but you can figure out the problem. And if you try to print page ' http://expressjs.com/ ', the same problem occurred. So it is not because of some specific pages cause the problem, it seems more a general issue. 
![normal_phantomjs_binary](https://cloud.githubusercontent.com/assets/4759678/9717378/d6bc1e36-55a4-11e5-8d49-4e78596007a2.jpg)
![desktape_phantomjs_binary](https://cloud.githubusercontent.com/assets/4759678/9717381/d9e35d9a-55a4-11e5-94d2-8912c8ccb22a.jpg)

**Comment by VinceZK** [comment]
And I tested to snapshot images (.png), it works fine. So it only effects .pdf snapshots.

**Comment by astefanutti** [comment]
@VinceZK I've tested the `examples/rasterize.js` script with the PhantomJS 2.0.0 Mac OS X official binary and the DeckTape Mac OS X binary and cannot see any differences for PDF output on http://expressjs.com/ and http://www.jrj.com.cn. What version of PhantomJS _normal_ binary are you using?

That being said, DeckTape is meant to be used to export HTML presentations to PDF. If this issue is meant to be provided with PhantomJS Linux CentOS binary from the PhantomJS official code line, I would suggest you contact PhantomJS project support directly.

**Comment by VinceZK** [comment]
@astefanutti I did more tests, and found if you set page format to 'A4', it will reproduce the error. 
Please try command line:  $phantomjs examples/rasterize.js http://www.jrj.com.cn out.pdf A4

Maybe DeckTape is free of the issue. But the official code line has no confirmed schedule to the "link" issue. I'd like to take some time to figure it out based on your code line. 

Thanks anyway:-)
