### ISSUE TITLE
Decktape giving spurious errors with Webm videos

### ISSUE THREAD

**Issue by chrish42** [astefanutti/decktape#153]
I have an animated GIF (well, as a Webm video) in one of the slides for my presentation. When running decktape on it, the PDF is fine, but I get spurious errors, which are a bit confusing:

```
Loading page http://christianhudon.name/talks/tour-of-ml-tech/slides.html ...
[object Object]

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm
Loading page finished with status: 200
Remark JS plugin activated
Printing slide #27      (27/27) ...
Printed 27 slides
```

Here's the slide in question and the presentation: http://christianhudon.name/talks/tour-of-ml-tech/slides.html#2

**Comment by astefanutti** [comment]
It seems the presentation renders actually fine.

I can replicate that behaviour with Chrome directly that returns some 206 _Partial Content_ multiple times. For some reasons, Puppeteer handles these by emitting the `requestfailed` event with the `net::ERR_ABORTED` failure message.

It'd be great you open an issue in the Puppeteer tracker here https://github.com/GoogleChrome/puppeteer.

**Comment by chrish42** [comment]
Opened issue https://github.com/GoogleChrome/puppeteer/issues/2701 over there about this. If there's anything else that should be mentioned, feel free to add it there. (I don't know a whole lot about the npm world...) Thanks!

**Comment by aslushnikov** [comment]
@astefanutti @chrish42 hi guys, I'm coming here from the https://github.com/GoogleChrome/puppeteer/issues/2701.

> I can replicate that behaviour with Chrome directly that returns some 206 Partial Content multiple times. 

How do you replicate this? Or am I too late and the presentation has already changed?

**Comment by chrish42** [comment]
@aslushnikov When I was doing this, I was working on the final version of the presentation. So the URL in my initial report should still trigger the problem. If you can't reproduce it with that link, I'll check when I'm back at work on Tuesday (to use my existing install).

**Comment by aslushnikov** [comment]
@chrish42 I'll help a lot if you can come up with a puppeteer script that reproduces the problem. Please, feel free to post the repro in the puppeteer issue you filed once you have time.

**Comment by chrish42** [comment]
@aslushnikov I'm just a user of puppeteer, through decktape, but I'll see what I can do if @astefanutti (the author of decktape) doesn't answer here.

**Comment by astefanutti** [comment]
>> I can replicate that behaviour with Chrome directly that returns some 206 Partial Content multiple times.

> How do you replicate this? Or am I too late and the presentation has already changed?

@aslushnikov, by opening the network tab from DevTools and loading http://christianhudon.name/talks/tour-of-ml-tech/slides.html, it seems Chrome returns 206 while loading the webm resource.

For some reasons, Puppeteer handles the 206 code by emitting the `requestfailed` event with the `net::ERR_ABORTED` failure message.

**Comment by aslushnikov** [comment]
I occasionally see loading of these resources canceled: 
![image](https://user-images.githubusercontent.com/746130/42918922-5a4b9bc6-8ac4-11e8-98ac-87675b902d5e.png)

This might happen if there's a video tag that gets detached from DOM, or if its src gets changed.
So it looks like there's no actual issue here.

**Comment by astefanutti** [comment]
Thanks @aslushnikov.

I've just added a special case to not output error reported back by Puppeteer on cancelled requests in 6e98851d8b62a22328c8cbdfc42e870fb9394d7b.
