### ISSUE TITLE
docker: mounting of local storage

### ISSUE THREAD

**Issue by pat-s** [astefanutti/decktape#156]
Only works for me when using `-v $HOME:$HOME` instead of `-v ~:/home/user` when trying to write locally.

Otherwise I get: 

`volume name is too short, names should be at least two alphanumeric characters`

**Comment by astefanutti** [comment]
It seems like a Docker issue moby/moby#20122.

Either your Docker version may be out-dated or your shell does not do tilde expansion before passing the argument.

Anyway, I don't see anything that could be done on DeckTape side.
