### ISSUE TITLE
`document.origin` is deprecated

### ISSUE THREAD

**Issue by mspittler** [astefanutti/decktape#161]
I wanted you to notify that there are changes in some dependencies. This is what I get after running:

`document.origin is deprecated and will be removed in M70, around October 2018. Please use self.origin (window.origin) instead. See https://www.chromestatus.com/features/5701042356355072 for more details.`

Thanks!

**Comment by astefanutti** [comment]
Thanks for the report.

This is reported by Chrome whenever a presentation depends on that API. It depends on the presentation and I don't think there is anything that can be done on DeckTape side. Depending on the presentation framework you're using, you may want to report to it directly.

Based on that, I'd be inclined to close this. Thanks again.
