### ISSUE TITLE
Sandbox Failure in PDF Generation

### ISSUE THREAD

**Issue by ztroop** [astefanutti/decktape#165]
`decktape`: 2.8.9
`chromium`: 69.0.3497.100 (Official Build) Arch Linux (64-bit)
`node`: 8.9.4

```
node /path/to/slides/node_modules/decktape/decktape.js -p 1000 file:///path/to/slides/.tmp/pdf/presentation.html pdf/presentation.pdf
```

```
Error: Failed to launch chrome!
[0928/161849.922445:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55741f07c8ec base::debug::StackTrace::StackTrace()
#1 0x55741eff8200 logging::LogMessage::~LogMessage()
#2 0x5574204eb4f0 service_manager::ZygoteHostImpl::Init()
#3 0x55741ecbf54e content::ContentMainRunnerImpl::Initialize()
#4 0x55741ecf2eb8 service_manager::Main()
#5 0x55741ecbdd91 content::ContentMain()
#6 0x5574231c597d headless::(anonymous namespace)::RunContentMain()
#7 0x5574231c5a08 headless::HeadlessBrowserMain()
#8 0x55741ecf04ab headless::HeadlessShellMain()
#9 0x55741d0b51ac ChromeMain
#10 0x7f056f5e5223 __libc_start_main
#11 0x55741d0b502a _start

Received signal 6
#0 0x55741f07c8ec base::debug::StackTrace::StackTrace()
#1 0x55741f07c451 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f05728413c0 <unknown>
#3 0x7f056f5f8d7f __GI_raise
#4 0x7f056f5e3672 __GI_abort
#5 0x55741f07b275 base::debug::BreakDebugger()
#6 0x55741eff8669 logging::LogMessage::~LogMessage()
#7 0x5574204eb4f0 service_manager::ZygoteHostImpl::Init()
#8 0x55741ecbf54e content::ContentMainRunnerImpl::Initialize()
#9 0x55741ecf2eb8 service_manager::Main()
#10 0x55741ecbdd91 content::ContentMain()
#11 0x5574231c597d headless::(anonymous namespace)::RunContentMain()
#12 0x5574231c5a08 headless::HeadlessBrowserMain()
#13 0x55741ecf04ab headless::HeadlessShellMain()
#14 0x55741d0b51ac ChromeMain
#15 0x7f056f5e5223 __libc_start_main
#16 0x55741d0b502a _start
  r8: 0000000000000000  r9: 00007ffcbc4a86b0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffcbc4a8ed8 r13: 0000000000000161 r14: 00007ffcbc4a8ee0 r15: 00007ffcbc4a8ee8
  di: 0000000000000002  si: 00007ffcbc4a86b0  bp: 00007ffcbc4a8900  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f056f5f8d7f  sp: 00007ffcbc4a86b0
  ip: 00007f056f5f8d7f efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/path/to/slides/node_modules/puppeteer/lib/Launcher.js:333:14)
    at Interface.helper.addEventListener (/path/to/slides/node_modules/puppeteer/lib/Launcher.js:322:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

If I add `--no-sandbox` to the list on line 207, it will work as expected. However, I don't like living dangerously and it should function without disabling the sandbox.

**Comment by astefanutti** [comment]
The recommended solution is to enable user namespaces in your kernel.

It is possible to pass `--no-sandbox` as CLI option. As you've mentioned, it's not ideal security wise. Unfortunately, there is nothing much that can be done at DeckTape level.

Duplicates #103.

**Comment by ztroop** [comment]
Seeing as it's come up a couple of times, maybe it might be worth noting as a requirement in the documentation? I'd happily make a PR for that if you like.

**Comment by astefanutti** [comment]
> Seeing as it's come up a couple of times, maybe it might be worth noting as a requirement in the documentation?

That's a very good idea. We've created a FAQ section in the README for that purpose. I think it'd be valuable to have an item about that issue there.

> I'd happily make a PR for that if you like.

Definitely!

**Comment by allsey87** [comment]
I had a very similar error message to what was reported above, however, it seems that it was not a sandbox related issue. I just needed to pass the path to chrome in the arguments of decktape and everything worked for me.

```bash
decktape reveal file:///home/user/presentation/index.html#/ output --chrome-path /opt/google/chrome/chrome
```

I am running Arch Linux with the 4.20.13 kernel. Decktape installed with: ```sudo npm install --unsafe-perm -g decktape```. Relevant packages and versions are:
1. c-ares-1.15.0-1
2. node-gyp-3.8.0-1
3. nodejs-11.12.0-1
4. semver-5.6.0-1
5. npm-6.9.0-1
6. hummus@1.0.95
7. puppeteer@1.12.2
8. decktape@2.9.2

**Comment by astefanutti** [comment]
@allsey87 using `--chrome-path` by-passes the Chromium instance installed with Decktape to using another installation that may be setup in such a way it can use sandboxing.

**Comment by allsey87** [comment]
That makes sense. Passing the ```--no-sandbox``` wasn't making any difference for me. I kept getting the error reported above. 

> Error: Failed to launch chrome!
[0928/161849.922445:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

I think using an existing/working chrome installation is good work around for the time being. That's why I added the above info.

**Comment by astefanutti** [comment]
There has been a change in the way you can pass argument to Chromium. For instance, to disable sandboxing, you should now be using `--chrome-arg=--no-sandbox`. That being said, relying on a distro installed Chromium instance is a good solution too, maybe worth documenting...
