### ISSUE TITLE
Navigation timeout exceeded - what to do?

### ISSUE THREAD

**Issue by nilsnolde** [astefanutti/decktape#166]
Hi,
it finally worked:) Now stuck with another error. Can you pls let me know how to circumvent this one:

```bash
Kernel: kernel_connected (d0a7c891-120e-4767-907e-b0a307956658)
Kernel: kernel_ready (d0a7c891-120e-4767-907e-b0a307956658)
HTML Sanitizer span.style changed { change: 'changed',
  tagName: 'span',
  attribName: 'style',
  oldValue: 'font-size: 1.1em; font-weight: bold;',
  newValue: 'font-size: 1.1em ; font-weight: bold' }
Loading extension: jupyter-js-widgets/extension

TimeoutError: Navigation Timeout Exceeded: 60000ms exceeded
```

I used this command via RISE:
```bash
`npm bin`/decktape -s 2550x1434 http://localhost:8888/notebooks/src/SOTM18.ipynb?token=b8bdee4ef7b0089db283e1ca96e8b3f158406c1d88ce8bdb ../python/sotm2018/src/SOTM18.pdf
```
The notebook is quite heavy on maps and I had to downscale quite a lot. It worked when I didn't have maps rendered in the notebook.

Is there a setting in `.js` files that I can tweak to extend the time beyond 1 min?

Thanks
Nils

**Comment by nilsnolde** [comment]
Never mind, found it:
[decktape.js:L231](https://github.com/astefanutti/decktape/blob/0e78f8273b4aa292d39d5009e654c2f66f17895e/decktape.js#L231)  `page.goto(options.url, { waitUntil: 'networkidle0', timeout: 60000 })`

And that actually worked, didn't even take 2 mins. Just slightly longer than the default 1 min.

**Comment by astefanutti** [comment]
We may want to consider adding a CLI option to control the timeout.

**Comment by ctritten** [comment]
Would it be possible to integrate this timeout option in a next release?

**Comment by astefanutti** [comment]
@ctritten sure, if you can submit a PR, I'll merge it and cut a new release ASAP.
