### ISSUE TITLE
Cannot generate PDF Reveal Angular

### ISSUE THREAD

**Issue by mateusvbf** [astefanutti/decktape#168]
Hello, i'm trying to generate pdf with a reveal presentation running locally with angular but when i run

`decktape reveal http://localhost:4200/.../... test.pdf`
 
it returns me

`Loading page finished with status: 200
Reveal JS plugin activated
Error: Evaluation failed: TypeError: Cannot read property 'querySelectorAll' of undefined
    at getSlides (http://localhost:4200/scripts.bundle.js:4123:31)
    at Object.getTotalSlides (http://localhost:4200/scripts.bundle.js:4134:10)
    at _ (__puppeteer_evaluation_script__:2:16)`

thanks in advance, any help would be appreciated

**Comment by astefanutti** [comment]
It seems the call to the `Reveal.getTotalSlides()` API fails for some reasons.

What version of Reveal do you use?

Would you be able to share your presentation so that I can reproduce and troubleshoot?

**Comment by mateusvbf** [comment]
Reveal version is 3.7.0
also i logged `Reveal.getTotalSlides()` and it returns me the exact numbers of slides i have.
Maybe its because of Angular Route Guards i use in the presentation url? I didnt dived enough into the source of decktape to see how it access the url 

I'm affraid i cannot share the full presentation with you due to information security issues, but i paste some some pieces below
Thanks for the early reply

```
import * as Reveal from 'reveal.js';

 ngOnInit() {
    /*some code here*/
    this.initializeReveal();
  }

initializeReveal() {
    Reveal.initialize(
      {
        display: 'block',
        controlsTutorial: true,        
        width: "100%",
        height: "100%",
        center: true,
        touch: true,
        progress: false,
        controlsBackArrows: 'faded',
        minScale: 1,
        maxScale: 1
      }      
    );

/*some Reveal listeners to make http requests*/
}
```

**Comment by astefanutti** [comment]
It's likely due to the Reveal initialisation being done in `ngOnInit` callback.

Reveal may expose some lifecycle callback so that DeckTape can delay exporting the slides until it's initialised.

**Comment by mateusvbf** [comment]
Im testing alternatives to ngOnInit, if it works i post here

**Comment by mateusvbf** [comment]
It was a authentication problem. Just tested a pdf export with a reveal presentation only and it worked fine. Thanks for the replies! Closing the issue now as it is not a problem with decktape itself
