### ISSUE TITLE
decktape proxy setting to Puppeteer 

### ISSUE THREAD

**Issue by cderv** [astefanutti/decktape#169]
Hi, 

I try to use decktape in docker and behind a proxy. It seems that proxy settings by environment variables are not taken into account and that I need to pass `--proxy-server` arguement to `chromium-browser`. In a way this is related to #130 as we can't pass other args to Puppeteer that the two whitelisted.

with `chromium-browser` inside the decktape docker container, with all the env var set I get an error pointing to this: https://bugs.chromium.org/p/chromium/issues/detail?id=16709. If I set `--proxy-server` argument in `chromium-browser`, it is ok. When (and if) #130 is made possible, I could try again to see if this fixes the issue.

**Comment by astefanutti** [comment]
Thanks for the report. I'll address it with #130 so that Decktape provides a generic way to pass Puppeteer options from the CLI.

**Comment by astefanutti** [comment]
#130 has been fixed with 6b46a957801ddc518133df24a9c73acf6bc968f5. Let me close this.
