### ISSUE TITLE
Module printer not found? 

### ISSUE THREAD

**Issue by Martin-Jung** [astefanutti/decktape#17]
Hi there,

I try to make a pdf out of a reveal.js presentation. Haven't used phantomjs before and thus had to compile it myself (running linux debian 7.0).
The subsequent call to decktape however returns some strange error messages:
Call:
`bin/phantomjs decktape.js reveal.js http://127.0.0.1:8001/index.html out.pdf`

```javascript
Error: Cannot find module 'printer'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require `
```

**Comment by astefanutti** [comment]
Have you compiled PhantomJS from the [forked version](https://github.com/astefanutti/phantomjs) that contains improvements and the `printer` module that DeckTape leverages?

You may find more information in the [Build](../#build) section.

**Comment by Martin-Jung** [comment]
I have not... Thanks, will try and close if successful ;)

**Comment by astefanutti** [comment]
Would you mind uploading your Debian 7 binary version in the [downloads](../tree/gh-pages/downloads) directory so that others can benefit from it?

**Comment by Martin-Jung** [comment]
Sure, but it is rather big in comparison? Compiled bin is around 57mb. 
Maybe I forgot some special flags ?

**Comment by astefanutti** [comment]
Indeed, you just have to compress the file with [UPX](http://upx.sourceforge.net).

**Comment by Martin-Jung** [comment]
Reduced filesize to about 20mb. Added and created pull.
I am actually running debian 8 - jessie.
