### ISSUE TITLE
"Error: Read ttf table data error"

### ISSUE THREAD

**Issue by pferreir** [astefanutti/decktape#175]
I'm trying to convert a presentation to PDF:

```
$ decktape automatic http://localhost:8001 out.pdf
Loading page http://localhost:8001 ...
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/4/1    (19/24) ...
Error: Read ttf table data error
```

I can't find any reference to this error in the wild. I can share my presentation if that helps.

**Comment by jacklenox** [comment]
I'm having the same problem. Attaching my presentation.
[Building-for-sustainability-with-WordPress.zip](https://github.com/astefanutti/decktape/files/2857385/Building-for-sustainability-with-WordPress.zip)

**Comment by astefanutti** [comment]
@jacklenox Thanks. I've just tried exporting your presentation and have not been able to reproduce the error. Could you try with version 2.9.2 and provide your environment details?

**Comment by astefanutti** [comment]
Let's follow up a similar error tracked in #202 and close this.
