### ISSUE TITLE
docker error on centos 7

### ISSUE THREAD

**Issue by pat-s** [astefanutti/decktape#178]
`docker run hello-world` works fine. Any idea if this issue is related to decktape?

```sh
docker run --rm -t -v `pwd`:/slides astefanutti/decktape http://lab.hakim.se/reveal-js slides.pdf

docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/slides\") set in config.json failed: permission denied": unknown.
```

**Comment by astefanutti** [comment]
It looks like mounting `$(pwd)` to the `/slides` directory failed for some reasons. I don't think that's related to Decktape though.

**Comment by astefanutti** [comment]
Let me close this. You can try running the command without the mount to check it's a Docker issue, e.g.:

    $ docker run --rm -t astefanutti/decktape http://lab.hakim.se/reveal-js slides.pdf

**Comment by pat-s** [comment]
I'll come back to this issue later. For now I just did it locally on my machine rather than on the remote one with CentOS.
