### ISSUE TITLE
TypeError: stream.setPosition is not a function

### ISSUE THREAD

**Issue by helloncanella** [astefanutti/decktape#179]
Issuing this command `decktape --slides 1-2 https://webslides.tv/\#slide\=1 ./here.pdf`, results in

```
Loading page https://webslides.tv/#slide=1 ...
Loading page finished with status: 200
WebSlides plugin activated
Printing slide #0       (1/8) ...
TypeError: stream.setPosition is not a function
```

**Comment by astefanutti** [comment]
I've tried running the command but haven't been able to reproduce the error. Could you please provide the version of DeckTape you're using and your environment? Would you mind trying to re-install DeckTape and provide the installation log?

**Comment by helloncanella** [comment]
I've reinstalled using npm, and it works.

Initially I've used yarn...

**Comment by astefanutti** [comment]
Great. Glad it works now.
