### ISSUE TITLE
Emojis in URL fragment breaks navigation

### ISSUE THREAD

**Issue by gabyx** [astefanutti/decktape#182]
Haveing the following Slide in my Presentation in RevealJS;
```html
<section>
        <h1>Disclaimer</h1>
        <p class="fragment current-only">Cuztomized with ❤️</p>
</section>
```
Does not work and outputs the error:
```bash
Loading page http://localhost:3000 ...
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/5      (6/6) ...not support cmap format:14

URIError: URI malformed
```
removing the emoji, everything works.

**Comment by astefanutti** [comment]
It seems related to GoogleChrome/puppeteer#668. The emoji in the URL fragment breaks Puppeteer navigation.

**Comment by gabyx** [comment]
As a workaround `<i class="emoji">❤️</i>`
with EmojiOne Font as Css works.

**Comment by JPtenBerge** [comment]
I've tried to pin down what's causing the error. It doesn't seem to be Puppeteer. It's this line that causes the error:

	const font = Font.create(buffer, { type: 'ttf', hinting: true });

To give a bit of context, here is a bit more code. It's from `decktape.js`, starting at line 405.

	// Consolidate duplicate fonts
	function parseFont(fontObject) {
		const pdfStreamInput = cpyCxtParser.parseNewObject(fontObject.getObjectID());
		const fontDictionary = pdfStreamInput.toJSObject();
		
		// See "Introduction to Font Data Structures" from PDF specification
		if (fontDictionary.Subtype.value === 'Type0') {
		// TODO: properly support composite fonts with multiple descendants
		const descendant = cpyCxtParser
			    .parseNewObject(fontDictionary.DescendantFonts.toJSArray()[0].getObjectID())
			    .toJSObject();
		if (descendant.Subtype.value == 'CIDFontType2') {
			const descriptor = cpyCxtParser
			    .parseNewObject(descendant.FontDescriptor.getObjectID())
			    .toJSObject();
			const id = descriptor.FontFile2.getObjectID();
			const buffer = readStream(cpyCxtParser.parseNewObject(id));
			const font = Font.create(buffer, { type: 'ttf', hinting: true });

**Comment by astefanutti** [comment]
Thanks a lot for the input. I'm not entirely sure the `not support cmap format:14` message is the cause of the `URIError: URI malformed`. I need to dig into it.

`fonteditor-core` was the most robust font parsing OSS library I could find a couple of years ago. It is possible to switch to another library if one exists that's more robust.

**Comment by astefanutti** [comment]
I've successfully exported the following RevealJS presentation with the latest 3.4.0 version:

```html
<div class="reveal">
	<div class="slides">
		<section>Slide 1</section>
		<section>Slide 2</section>
		<section>
			<h1>Disclaimer</h1>
			<p class="fragment current-only">Cuztomized with ❤️</p>
		</section>
	</div>
</div>
```

```
Reveal JS plugin activated
Printing slide #/2      (3/3) ...
Printed 3 slides
```

Here is the output PDF: [test.pdf](https://github.com/astefanutti/decktape/files/7624447/test.pdf).

Feel free to re-open if that's still an issue.
