### ISSUE TITLE
when using ?print-pdf, only first page is printed

### ISSUE THREAD

**Issue by cyberic99** [astefanutti/decktape#190]
Hello

I'd like to export a reveal.js presentation using the 'print.css'  stylesheet.

When I add ``?print-pdf`` to the url, the generated pdf contains only the first slide

**Comment by astefanutti** [comment]
The `print-pdf` query parameter layout the slides specifically to be printed, in _one_ Web page. Decktape operates differently by exporting each slides and merging them into a single PDF. So the `print-pdf` parameter is not meant to be used with Decktape. Is there any reason you need it?

**Comment by cyberic99** [comment]
in fact, I'd like to export a normal pdf with a background, and another one with no background.

I use the print-pdf param to switch to the print.css with no background.

Maybe there is a way to specify an alternative css file w

**Comment by astefanutti** [comment]
If this is a presentation you own, you can adapt the print stylesheet loading by adding an option to load an alternative CSS file specifically for Decktape: https://github.com/hakimel/reveal.js#print-stylesheet.

That being said, Decktape could expose an option to inject external CSS stylesheets into the presentation. That could be useful when it's not easy to change the presentation source.

**Comment by cyberic99** [comment]
> you can adapt the print stylesheet loading by adding an option to load an alternative CSS file specifically for Decktape

Yes, that it what I did

About injecting a css, it could be a good idea, but I wonder how it can be implemented in a generic way

**Comment by astefanutti** [comment]
Some CSS are already being injected for Remark:

https://github.com/astefanutti/decktape/blob/a9d894da4f48c0e397d0d278869178084b1e9743/plugins/remark.js#L29-L46

The same technic could be used to inject stylesheets loaded form a file locally or from an URL or even inlined.

If you think that's worth, could you please create a separate issue to track that feature and maybe close this one?

**Comment by cyberic99** [comment]
Done here: https://github.com/astefanutti/decktape/issues/191

**Comment by astefanutti** [comment]
Thanks!
