### ISSUE TITLE
Docker: Cannot create pdf in latest tag due to "browser has disconnected"

### ISSUE THREAD

**Issue by p-oswald** [astefanutti/decktape#194]
While creating a pdf with the latest docker tag I ran into this error:

> Error: Navigation failed because browser has disconnected!

The command to create the pdf is as follows:
```
$ docker run --rm -t -v `pwd`:/slides -v /home/user/reveal/:/home/user astefanutti/decktape /home/user/index.html slides.pdf
```

The command works fine when I use it with the tag 2.9.

**Comment by astefanutti** [comment]
I haven't been able to reproduce with version 2.10.0. Could you please give it a try? Otherwise, could you provide details on your environment, like OS and Docker version?

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if that is still an issue.
