### ISSUE TITLE
Generated PDF only renders shapes of emojis (on Linux)

### ISSUE THREAD

**Issue by Bagira80** [astefanutti/decktape#200]
I created a very simple *reveal.js* [presentation](https://github.com/Bagira80/reveal.js/tree/decktape-emoji-problems) containing emojis (using the "Noto Color Emoji" font, which is the default emoji-font in Chrome/Chromium).  
It looks like this:

![Presentation](https://github.com/Bagira80/reveal.js/raw/decktape-emoji-problems/Presentation.png)

When using *Decktape* to generate a [PDF](https://github.com/Bagira80/reveal.js/raw/decktape-emoji-problems/decktape-output.pdf) from the presentation, the resulting PDF looks as it should when displayed using browsers (Chrome, Chromium, Firefox, Edge) but using "normal" (Linux) PDF-viewers (as e.g. *evince*) the resulting PDF looks quite weird:

![Weird Presentation](https://github.com/Bagira80/reveal.js/raw/decktape-emoji-problems/Weird_PDF.png)

Only the shapes of the emojis are displayed but not the colors on top.

When looking at the embedded fonts, the PDF-viewer (*evince*) tells me that all fonts are embedded, but the names seem to be unrecognizable (and the encoding probably unknown):

![List of embedded fonts](https://github.com/Bagira80/reveal.js/raw/decktape-emoji-problems/Embedded_fonts.png)

I am not sure if this is just a problem with the PDF viewers I tried under Linux (*evince*) or the backend-library (*cairo*?) used by it (see https://victor.kropp.name/blog/emoji-on-linux/) or if *decktape* does not embed the emoji fonts properly.

Maybe you could give me a hint?

**Comment by astefanutti** [comment]
Emojis should be working with Decktape. To find out whether it's caused by Decktape or the reader, could you please print the slide with Chrome or your Web browser and opens the exported PDF?

**Comment by Bagira80** [comment]
> Emojis should be working with Decktape. To find out whether it's caused by Decktape or the reader, could you please print the slide with Chrome or your Web browser and open the exported PDF?

That is a good idea.

When printing the slides with Chrome the resulting file looks fine when displayed with Chrome or another browser, but looks weird again with the native PDF viewer (*evince*). The names of the embedded fonts are missing again, though.

So, I guess, *Decktape* is doing everything correct and only the PDF viewer has problems displaying the emojis correctly.

Thank's for your help! :nerd_face:

**Comment by astefanutti** [comment]
Thanks for the feedback. Another test is to open the PDF with Acrobat Reader if you have it installed, as it is supposed to follow the PDF spec closely.

**Comment by Bagira80** [comment]
A colleague of mine did this. (I do not have Adobe Reader installed.)  
It looked just fine there, too.

So, I do assume that *Decktape* is just doing it right and *evince* has some problems.

I already created a bug-report in the issue-tracker of *evince*: https://gitlab.gnome.org/GNOME/evince/issues/1300

**Comment by elliot-sawyer** [comment]
I added some extra info about this over here: https://github.com/astefanutti/decktape/issues/209#issuecomment-2387696684

Here's a sample page in Chromium:
![image](https://github.com/user-attachments/assets/1ce03ab9-6ae7-4061-b201-676b8496c00a)

Here's the same page produced as a PDF with Linux Document Viewer:
![image](https://github.com/user-attachments/assets/e3e05c6b-e686-432f-a3af-85468007891d)

But if I view the same PDF in Edge, Chromiuim, or Firefox, it renders correctly:
![image](https://github.com/user-attachments/assets/09a535ec-0e9b-4eee-bca3-aa00eccdc621)

I'm mainly leaving this comment here, as a reminder that the software you're using the view the PDF's matters
