### ISSUE TITLE
Endless loop when converting from reveal.js per docker container

### ISSUE THREAD

**Issue by tkleiber** [astefanutti/decktape#203]
Hi!

Assuming following testcase for docker:

```
docker run --rm -t -v `pwd`:/slides https://zenika.github.io/adoc-presentation-model/reveal/reveal-my-asciidoc.html?fragments=false presentation.pdf
```

The call never returns. If I stop the docker container from another session 

```
docker stop 4d0dc3b8bfc9
```

I can see similar output to:

```
Loading page https://zenika.github.io/adoc-presentation-model/reveal/reveal-my-asciidoc.html?fragments=false ...
Failed to load resource: the server responded with a status of 404 ()
Failed to load resource: the server responded with a status of 404 ()
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/12     (123/54) ...
Printing slide #/12     (124/54) ...
Error: Protocol error (Page.printToPDF): Target closed.
```
The mentioned page 12 is the last page of the presentation and it seems it is created 124-54=70 times in the pdf till killing the docker container:

https://zenika.github.io/adoc-presentation-model/reveal/reveal-my-asciidoc#/12

Unfortunatly the pdf is corrupt after killing docker container, so all I have is the output above.

Kind regards
Torsten

**Comment by akosma** [comment]
Same error here

**Comment by akosma** [comment]
I solved the issue in my case by checking the HTML markup of the presentation; when invalid, the PDF generation would enter in an infinite loop (for info, I'm generating the HTML via asciidoctor-revealjs with a bunch of custom plugins, which were at the origin of the issue)

**Comment by astefanutti** [comment]
Thanks a lot for the feedback. I was having a look at the issue and found also that the HTML may be invalid. That leads to breaking the `Reveal.isLastSlide()` Reveal API.

As a work-around, it is possible to use the `--slides` option, e.g.:

    $ docker run --rm -t -v `pwd`:/slides https://zenika.github.io/adoc-presentation-model/reveal/reveal-my-asciidoc.html test.pdf --slides 1-54

You may also want to apply the work-around for #151 by increasing the export size.

**Comment by tkleiber** [comment]
Thanks, both workarounds works for now for me. I will check now, why my HTML markup is not valid, and yes - I use a lot of reveal plugins too!
