### ISSUE TITLE
H1 titles look ugly in the exported PDF under certain conditions

### ISSUE THREAD

**Issue by jmuheim** [astefanutti/decktape#211]
When H1 titles are long, they tend to look ugly in the exported PDF.

For example, in the exported HTML, the title looks good:

![image](https://user-images.githubusercontent.com/1814983/81817482-1533ba80-952d-11ea-9a7f-0b6090d4c574.png)

Also in the exported screenshot (with 4:3 dimension) it looks good:

![image](https://user-images.githubusercontent.com/1814983/81817250-bbcb8b80-952c-11ea-8320-552f97302674.png)

But in the PDF it looks bad:

![image](https://user-images.githubusercontent.com/1814983/81817277-c9811100-952c-11ea-8fa0-1ac9c41c208c.png)

Could it have to do with the default widescreen resolution of the PDF (see #210)?

**Comment by jmuheim** [comment]
I now manually decreased the font size of H1, now it looks better:

![image](https://user-images.githubusercontent.com/1814983/81819549-bf144680-952f-11ea-9eac-0c350ad41b28.png)

Still this might be a problem somebody wants to look into.

**Comment by astefanutti** [comment]
@jmuheim what presentation framework do you use?

**Comment by astefanutti** [comment]
Chances are it's related to #151 that's been fixed in DeckTape 3.7.0.

Let me close this. Feel free to re-open if you still face this issue after upgrading DeckTape.
