### ISSUE TITLE
Running within Docker unable to reach localhost server

### ISSUE THREAD

**Issue by colindean** [astefanutti/decktape#215]
This did not work for me:

    docker run --rm -t --net=host -v `pwd`:/slides astefanutti/decktape http://localhost:8000 slides.pdf

This worked for me:

    docker run --rm -t --net=host -v `pwd`:/slides astefanutti/decktape http://192.168.65.2:8000 slides.pdf

I don't really know enough about Docker networking to understand why. I know that the container runs within Docker's network on 192.168.65.3, but I am under the impression that `--net=host` is supposed to let the container pretend that it's the host.

**Comment by astefanutti** [comment]
You may find some useful information at https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach. The solution may depend on your OS. If you find something relevant, it may be worth adding it to the _troubleshooting_ documentation.

**Comment by colindean** [comment]
Thanks for the pointer. `host.docker.internal` worked for me on macOS.

**Comment by astefanutti** [comment]
Thanks for the feedback. Happy to accept a PR if you think that's worth it.

**Comment by astefanutti** [comment]
Fixed with #217.
