### ISSUE TITLE
Navigatable TOC tree in the PDF for reveal slides 

### ISSUE THREAD

**Issue by olberger** [astefanutti/decktape#222]
Reveal.js allows using a 2D tree of sections/subsections.

When displayed to the screen, this leads to browsing along the 2 dimensions

When printed, all slides must be printed (usually), but it may be handy to embed inside the PDF a navigatable TOC of the slides to allow quickly pointing to a session start, skipping the subsections, etc.

Thanks in advance, if that can be made possible.

**Comment by astefanutti** [comment]
That is a much wanted feature, that would be useful also for the other presentation frameworks. I think that relates to #171.

**Comment by astefanutti** [comment]
Let me close this and keep track in #171.
