### ISSUE TITLE
Decktape fails on presentation based on reveal.js 4

### ISSUE THREAD

**Issue by pfisterer** [astefanutti/decktape#223]
I have updated my slides to the latest version of reveal.js (4.0.2) and I'm using the latest docker image of [astefanutti/decktape](https://hub.docker.com/r/astefanutti/decktape) to export my slides to PDF:

```bash
$ docker pull astefanutti/decktape

$ docker run --rm -v "$PWD/__pdfs__:/slides" astefanutti/decktape reveal \
          http://localhost:5500/index.html /slides/out.pdf
```

After updating my slides, I get the following error:

```console
Loading page http://localhost:5500/index.html ...
Live reload enabled.
Registering handlers for toggle class on click
Failed to load resource: the server responded with a status of 404 (Not Found)
Loading page finished with status: 200

Error: Unable to activate the Reveal JS DeckTape plugin for the address: http://localhost:5500/index.html
```

Maybe this is related to one of the (breaking) changes listed here: [Upgrading From Version 3 to 4.0](https://revealjs.com/upgrading/).

**Comment by astefanutti** [comment]
Could you make sure that Reveal is not configured as embedded: https://revealjs.com/presentation-size/#embedded?

**Comment by pfisterer** [comment]
@astefanutti thank you. I've explicitly added `Reveal.initialize({	embedded: false /* , other stuff */ });` but it didn't change anything - it also seems to be the default value.

**Comment by astefanutti** [comment]
I've just tried on some examples from HEAD revision of Reveal master branch and it works: https://github.com/hakimel/reveal.js/tree/master/examples.

It seems the Decktape Reveal plugin cannot activate, meaning that it cannot find the `Reveal` global variable, which is quite surprising (though expected in _embedded_ mode).

I fail to find a possible cause. Would you be able to share your presentation so that I can troubleshoot the issue?

**Comment by pfisterer** [comment]
@astefanutti Thanks for pushing me in the right direction. I needed to export `Reveal` using `window.Reveal = Reveal`

I was using 

```JavaScript
<script type="module"> 
      import Reveal from 'dependencies/reveal.js/dist/reveal.esm.js';
</script>
```

So now, I use 

```JavaScript
<script type="module"> 
      import Reveal from 'dependencies/reveal.js/dist/reveal.esm.js';
      window.Reveal = Reveal
</script>
```

Thanks!

**Comment by astefanutti** [comment]
Thanks for the feedback. I'm glad it works!
