### ISSUE TITLE
Error: Could not find browser revision 768783.

### ISSUE THREAD

**Issue by Crowerade** [astefanutti/decktape#230]
When i try to export from reveal to pdf taping : 
`decktape file.html file.pdf`

I get the following error : 

```
Error: Could not find browser revision 768783. Run "npm install" or "yarn install" to download a browser binary.
  at ChromeLauncher.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/cjs/node/Launcher.js:86:23)
  at async /usr/lib/node_modules/decktape/decktape.js:193:19
```
Can anyone help me please ?

**Comment by astefanutti** [comment]
It seems the local Chromium browser is not installed and cannot be fetched.

I'd suggest to try re-installing Decktape, possibly by cleaning the `/usr/lib/node_modules/decktape` directory first.

**Comment by Crowerade** [comment]
> It seems the local Chromium browser is not installed and cannot be fetched.
> 
> I'd suggest to try re-installing Decktape, possibly by cleaning the `/usr/lib/node_modules/decktape` directory first.
> 
> I've found https://stackoverflow.com/questions/62820586/error-could-not-find-browser-revision-756035-run-npm-install that seems similar.

All right, it worked, thanks so much !

**Comment by astefanutti** [comment]
Thanks for the feedback, I'm glad it works!
