### ISSUE TITLE
Exported PDF has space when a line wraps

### ISSUE THREAD

**Issue by antmarge** [astefanutti/decktape#232]
I have a PDF with a line (a long link) that wraps to a new line. If copied from the browser slides, the link pastes as expected. However, in the exported PDF from deck tape, when the link is copied and pasted, it includes a space where the line wrapped. 

Attached is a zip file with an example html file and the resulting pdf upon export with decktape.
decktape <url> <output.pdf>

Any idea what's going on and how to fix it? Thank you!

[badlink_example.zip](https://github.com/astefanutti/decktape/files/6806001/badlink_example.zip)

**Comment by astefanutti** [comment]
What PDF reader do you use?

It seems the presentation doesn't actually contain a link, but readers, like Mac OS Preview, automatically add a link. I've tried with Preview, and the link indeed contains an extra space. So I'd rather think it's an issue with some readers, that do not handle wrapping links correctly.

**Comment by antmarge** [comment]
I see thanks for the input, I hadn't thought of it being a viewer issue. I
use Preview. Others do the same thing. Adobe Acrobat interprets it as a new
line.

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if needed.
