### ISSUE TITLE
TypeError: Cannot read property 'dict' of undefined

### ISSUE THREAD

**Issue by mpolitze** [astefanutti/decktape#233]
Hi! 

for one of my slide decks I am getting the following error from decktape

```
Printing slide #4       ( 4/23) ...TypeError: Cannot read property 'dict' of undefined
    at parseXObject (/decktape/decktape.js:393:28)
    at /decktape/decktape.js:384:42
    at Array.forEach (<anonymous>)
    at parseResources (/decktape/decktape.js:384:25)
    at parseXObject (/decktape/decktape.js:403:7)
    at /decktape/decktape.js:384:42
    at Array.forEach (<anonymous>)
    at parseResources (/decktape/decktape.js:384:25)
    at parseXObject (/decktape/decktape.js:403:7)
    at /decktape/decktape.js:384:42
```

If it helps, the slide at question is available here: https://gitlab-nrw-workshop-2021-04.gitlab.io/workshop/slides.html#4

I am a bit lost, it would be nice to have a hint why it fails.

**Comment by astefanutti** [comment]
For some reasons, the PDF generated out of slide #4 contains a reference that cannot be resolved. so the following call returns an undefined result:

https://github.com/astefanutti/decktape/blob/bb3c3a2b9378aeee43e0cf9572e091d346718ae5/decktape.js#L392

Interestingly, I've been able to produce a correct PDF by returning early and skipping the unresolved reference:

[test.pdf](https://github.com/astefanutti/decktape/files/7009763/test.pdf)

It would be interesting to understand what is special in slide #4 that leads to that undefined result.
