### ISSUE TITLE
Unable to activate the Reveal JS DeckTape

### ISSUE THREAD

**Issue by cenk1cenk2** [astefanutti/decktape#234]
Hello @astefanutti ,

Thanks for your work on this beautiful plugin, that saves me a lot of time.

Recently I have wrapped the reveal.js in react. But now it fails to find the reveal.js even though I specifically run it with reveal.js mode.

```json
{
    "export:pdf": "docker run --rm -t -v $(pwd)/exports:/slides --user 0 --network host astefanutti/decktape reveal --load-pause 5000 http://localhost:3000/?showNotes=separate-page presentations-web-development-grundlagen-introduction.pdf --size 1920x960"
}
```

What I can add to my configuration so that this gets working again. Any help is appreciated, even though this is a novelty case and not a bug report, I failed to find it on my own.

You can see the repository here.
https://github.com/cenk1cenk2/react-presentations

**Comment by cenk1cenk2** [comment]
Okay, I am so sorry. I was just missing Reveal in window object, that was why it was going crazy because it was referenced by reacts useRef hook.

**Comment by astefanutti** [comment]
Thanks for the feedback. I'm glad to hear it works.

**Comment by sadikyalcin** [comment]
How did you expose it to the window?

**Comment by cenk1cenk2** [comment]
Hey @sadikyalcin 

It was something to do implicitly as follows.

https://github.com/cenk1cenk2/react-presentations/blob/9d288b7427f133de02fc59bfe6af135f79b89fad/packages/react-reveal-base/src/components/RevealJS.tsx#L545
