### ISSUE TITLE
Add some e2e tests

### ISSUE THREAD

**Issue by nicojs** [astefanutti/decktape#253]
Hi, it's me again 🙋‍♂️

How would you feel about adding some e2e tests using screenshot snapshots? This is my idea:

- [ ] Add a testing harness with input directories where we run decktape on.
- [ ] Add playwright as a dependency and open the pdfs in a browser using [the workaround suggested by the playwright team](https://github.com/microsoft/playwright/issues/19253#issuecomment-1338955863)
- [ ] Open each page in the generated pdf and match the snapshots to the snapshot on the disk
- [ ] Add a CI pipeline where we run these snapshot tests
- [ ] Add a manual pipeline that can automatically update the snapshots, which you can efficiently run on a branch of your choice.

I use this approach in a couple of repositories, and it works great IMO. It would save you a lot of time as a maintainer and (hopefully) prevent regression.

**Comment by astefanutti** [comment]
That'd be awesome! It'll definitely help for non-regression testing all the plugins 👍🏼.
