### ISSUE TITLE
Would you be open to financial contributions?

### ISSUE THREAD

**Issue by nicojs** [astefanutti/decktape#255]
Hi @astefanutti, it's me again 👋

We have an open-source policy in our company. Would you be open to financial contributions? Since we're using decktape a lot, it would be our way of saying: "Thanks 🤗".  I can't promise anything since I'm just 1 employee 😶

**Comment by astefanutti** [comment]
Hello @nicojs, thanks for having such a policy in your company and proposing Decktape could benefit from it!

I'm already very satisfied with maintaining Decktape voluntarily. It's a way for me to contribute back to the open-source ecosystem, as I benefit so much from it. Having all these users, especially in the scientific community, is enough a reward to me. In that spirit, your contributions and your PRs, are already an awesome way to saying thanks 😊. This is the primary reason why I haven't enable sponsorship for the project. I could certainly do it if you insist 😃, but your non-financial contributions to the project are already more than enough 🙏🏼.

**Comment by astefanutti** [comment]
Let me close this as it's been answered. Thanks again for asking :)
