### ISSUE TITLE
Reveal remove transition

### ISSUE THREAD

**Issue by nicojs** [astefanutti/decktape#258]
I think we should remove the transition when navigating reveal slides:

```diff
    return this.page.evaluate(fragments => Reveal.configure({
        controls  : false,
        progress  : false,
        fragments : fragments,
+       transition: 'none',
      }),
```

Disabling the transition will disable the next-slide animation. This way, users can configure a shorter "pause", resulting in a much faster export.

Code here:

https://github.com/astefanutti/decktape/blob/2474dddfbbedf1eed93320423221ff99522e84cb/plugins/reveal.js#L33-L37

**Comment by astefanutti** [comment]
I agree it makes sense.
