### ISSUE TITLE
decktape/phantomJS fails with upgrade to Ubuntu 15.10

### ISSUE THREAD

**Issue by darribas** [astefanutti/decktape#29]
I had decktape happily running until I upgraded my Ubuntu box to 15.15. Then running the forked version of  `phantomjs` produces the following error:

```
./bin/phantomjs: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory
```

I'm thinking it's probably because that binary was compiled on ICU52 and the only version available on the Ubuntu 15.10 repos is 55? Any advice most appreciated.

Let me also take the opportunity to thank the developers for an awesome piece of code, I use decktape to generate pdf versions of all my lecture slides and works wonders!

**Comment by astefanutti** [comment]
Your understanding is correct. PhantomJS static build on Linux is a long story as per ariya/phantomjs#12948. To work around that issue, you can either:
- Use the Docker image as documented in https://github.com/astefanutti/decktape#docker
- Recompile the improved version of PhantomJS as documented in https://github.com/astefanutti/decktape#build.

If the above does not work for you, I'll try to provide a binary for Ubuntu 15.15 ASAP.

Thanks for the feedback. You may want to share some love and star the project ;)

**Comment by darribas** [comment]
I've tried compiling PhantomJS unsuccessfully, here's the error I get after a while having my desktop full-speed:

```%bash
collect2: error: ld returned 1 exit status
Makefile.jsc:98: recipe for target '../../bin/jsc' failed
make[2]: *** [../../bin/jsc] Error 1
make[2]: Leaving directory '/media/dani/baul/code/decktape/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile.JavaScriptCore:126: recipe for target 'sub-jsc-pro-make_first-ordered' failed
make[1]: *** [sub-jsc-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/media/dani/baul/code/decktape/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile:91: recipe for target 'sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered' failed
make: *** [sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered] Error 2
```

I'd rather have it running natively as I have the creation of pdf's on scripts that run not only on Linux but of OSX and there it works well as it is, so I'd prefer to stick to a cross-platform codebase.

Do you have any suggestions? I basically installed all the dependencies mentioned in the PhantomJS website:

```
sudo apt-get install build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev
```

Then from the decktape clone, I ran:

```
git submodule update --init --recursive
```

Navigated into the folder:

```
cd phantomjs
```

And ran the build script:

```
./build.sh
```

Note it's not `./build.py` as indicated in your instructions. Maybe that's it? But I couldn't find the python script.

Happily starred the project ;-)

**Comment by astefanutti** [comment]
Have you pulled the latest revision of DeckTape? You should have the `build.py` script which is the most recent way of building PhantomJS. So that'd be better if you'd use that script.

Unfortunately the error that you faced doesn't ring a bell to me. You may search / reach out the PhantomJS project directly.

On my side, I'll try having a reproducible Ubuntu build with a Docker image ASAP so that we can compare the set of installed libraries.

**Comment by darribas** [comment]
Sorry my bad!!! I was on an older version. I pulled the latest and the greatest, run `./build.py` and it worked!

Thanks very much for all the help and support!

**Comment by astefanutti** [comment]
Great!

I'll follow-up with the PhantomJS Linux static build issue. At some point, if no progress is made, I'll upload  a specific binary for Ubuntu 15.15 as well.

In the meantime I think it's safe closing this issue.
