### ISSUE TITLE
Docker setup doesn't have access to user fonts

### ISSUE THREAD

**Issue by obilodeau** [astefanutti/decktape#30]
When building using docker in Linux, fonts installed in `~/.local/share/fonts/` won't work. I guess a -v mount trick could be used. I decided to build phantomjs instead.

I haven't confirmed if docker has access to globally installed fonts.

**Comment by astefanutti** [comment]
Sorry for the delayed answer 😞.

The Docker containers do not have access to fonts installed on the host. As you've noted, you'll have to mount a data volume pointing to `~/.local/share/fonts/`.

Depending on your use case, one option that we may consider is to have some font packages pre-installed in the DeckTape Docker image for the most commonly used fonts.

Let me know your thoughts.

**Comment by astefanutti** [comment]
Let me close this. Do not to re-open it if needed.

**Comment by wietze** [comment]
Just for reference, since this image runs with `node` as user, the full path is `/home/node/.local/share/fonts`.

 I used the following to get default Microsoft fonts working:

```bash
wget --output-document fonts.zip https://www.w7df.com/files0/Windows7DefaultFonts.zip?dl=1 && unzip fonts.zip && rm fonts.zip
docker run (...) -v `pwd`/Windows7DefaultFonts:/home/node/.local/share/fonts (...)
```

**Comment by astefanutti** [comment]
@wietze thanks. I wonder if it would make sense to add these fonts to the Docker image.

**Comment by wietze** [comment]
I agree it might be helpful to others too (e.g. I needed it to get the Georgia font working), however this sort of thing is always tricky when it comes to licences...

**Comment by astefanutti** [comment]
Right. Otherwise we can add an item in the FAQ.
