### ISSUE TITLE
Exception thrown when using command and options together

### ISSUE THREAD

**Issue by lordofthejars** [astefanutti/decktape#31]
Running something like `./bin/phantomjs decktape.js -p 1000 generic http://localhost:8080/ a.pdf` gets the next exception: `Error opening /Users/user/git/decktape/generic: No such file or directory`

**Comment by astefanutti** [comment]
Thanks for the report. It's been fixed @e623da42e056c5025e9bc2fed62c4eef0b6ba62f.
