### ISSUE TITLE
Remark custom styles not applied on PDF

### ISSUE THREAD

**Issue by gillchristian** [astefanutti/decktape#310]
Here's a Remark presentation https://remark-custom-css.vercel.app/

In the last two slides I have some custom CSS to display the pictures side by side or in a grid.

<img src="https://github.com/astefanutti/decktape/assets/8309423/6ee809ee-499d-46fb-8d06-e389fbfcefe6" width="320" >

Here's the source code https://github.com/gillchristian/remark-custom-css/blob/master/index.html

However in the PDF the styles aren't applied:

<img src="https://github.com/astefanutti/decktape/assets/8309423/4410ae85-624d-44dd-a34b-848f99bc11b5" width="320">

Here's the generated file: https://github.com/gillchristian/remark-custom-css/blob/master/deck.pdf

I generated the file with Docker:

```bash
docker run \
  --rm -t \
  --net=host \
  -v `pwd`:/slides astefanutti/decktape remark https://remark-custom-css.vercel.app/ deck.pdf
```

Note: the print pdf (ie. "Save as PDF" from Chrome's print page menu) does respect the styles https://github.com/gillchristian/remark-custom-css/blob/master/print-pdf.pdf

**Comment by astefanutti** [comment]
The Remark plugin used to manipulate CSS rules to work-around some issues, but that does not seem to be necessary anymore.

I've created #313, that results with the following PDF for your presentation: [test.pdf](https://github.com/astefanutti/decktape/files/13256414/test.pdf).

I need to to some more testing to make sure that doesn't introduce any regression.

**Comment by gillchristian** [comment]
Ohh that's awesome! Thanks for the quick fix as well!
