### ISSUE TITLE
Bug: `npm ci` doesn't work with decktape@3.13.0

### ISSUE THREAD

**Issue by nicojs** [astefanutti/decktape#341]
Strange problem. It seems that `npm ci` doesn't work with the latest decktape release on linux and windows. 

![decktape](https://github.com/astefanutti/decktape/assets/1828233/d75f1a27-5f52-4f33-b5a0-4a8087304cf5)

This is probably a bug npm in combination with the [npm-shrinkwrap.json](https://github.com/astefanutti/decktape/blob/master/npm-shrinkwrap.json) file. 

This is my thinking
- You've used mac os to release decktape
- `npm-shrinkwrap.json` includes `fsevents`, because it is included on mac (and only mac).
- `npm install decktape` will install decktape ignoring the `fsevents`, because I'm installing on linux.
- `npm ci` failed because of a bug.

I'll create an issue over at npm.

In the meantime, is there some way to solve this problem?

**Comment by nicojs** [comment]
Already found the issue at npm side: https://github.com/npm/cli/issues/7622

**Comment by nicojs** [comment]
This reminded me of open issue #277... opened #342. I think it is time to lose the shrinkwrap file (or remember why it was important ;))

**Comment by astefanutti** [comment]
I vaguely remember some people were having issues with transitive dependencies installed with different versions from those compatible with Decktape. And at the time the suggested solution had been to publish that shrinkwrap file according to:
https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson. I’m not sure what’s the best practice nowadays.

**Comment by nicojs** [comment]
Shrinkwrap is not common nowadays. It was the only solution to have any influence on dependencies in the past. Since then we have lockfiles and the ability to override dependencies. Shrinkwrap is almost never used nowadays.

If you feel more comfortable you can make it a breaking change (major version bump). I think that is justified

**Comment by astefanutti** [comment]
Thanks. I think it’s OK from the compatibility perspective. We can release a new minor version and get feedback. It’s still not entirely clear how dependencies would exactly match without the shrinkwrap file when users install decktape. If it turns out users have issues with this, we can releases bug fixes.

**Comment by nicojs** [comment]
> It’s still not entirely clear how dependencies would exactly match without the shrinkwrap file when users install decktape.

They probably won't. You can lock your direct dependency versions (by not specifying a version range, as you're doing), but you don't influence the transient dependencies. However, this is what users expect because this is how the entire node-js ecosystem works. If any issues occur, we always have [`"overrides"` in package.json to help](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) as a workaround.

Are you planning on doing a new minor release soon?

**Comment by astefanutti** [comment]
> Are you planning on doing a new minor release soon?

I’m mostly AFK for the next couple of days. I’ll do a release right after that.
