### ISSUE TITLE
Replace video tag with an image

### ISSUE THREAD

**Issue by hadim** [astefanutti/decktape#4]
In Chromium and Firefox when you print the page `<video>` tag are replaced by the current image display by the tag. 

Would it be possible to do the same in decktape ?

**Comment by astefanutti** [comment]
Yes, that sounds logical and I guess this could be done at the level of Qt WebKit. DeckTape currently depends on a forked version of PhantomJS (https://github.com/astefanutti/phantomjs) so that it can be given a try.

**Comment by hadim** [comment]
So there is now way to add that directly in decktape.

Should I open an issue in https://github.com/ariya/phantomjs

**Comment by hadim** [comment]
And embed video in PDF are kind of a mess because Linux pdf viewer does not support it...

**Comment by astefanutti** [comment]
You can create an issue in PhantomJS though from my recent experience, Qt related issues tend to be overlooked. That may be more effective to directly report these points in Qt issue tracker directly:

https://bugreports.qt.io/browse/QTBUG

**Comment by hadim** [comment]
Done -> https://bugreports.qt.io/browse/QTBUG-46984

**Comment by hadim** [comment]
I close since it depends on QtWebkit.
