### ISSUE TITLE
Module printer not found

### ISSUE THREAD

**Issue by jensgro** [astefanutti/decktape#42]
As in Issue #17 I have a problem with the printer. I installed PhantomJS as told in the Build-section but nevertheless it doesn't work. 
Afterwards I saw that this tool isn't capable to work with Shower 2 but nevertheless I find it awkward that PhantomJS doesn't work although it is installed. Can there be a conflict with the installed "real" PhantomJS 2?

**Comment by astefanutti** [comment]
@jensgro that's really strange. If you confirm you use the binary as documented in the install section, you shouldn't be getting that error for sure. What exact binary are you using?

For Shower 2, they broke the API so the Shower plugin needs to be adapted. You can track progress on this in #35.

**Comment by jensgro** [comment]
I started "build.py" inside the folfer "phantomjs". And according to the Changelog I have installed PhantomJS 2.1.0.

**Comment by astefanutti** [comment]
If you build the forked version of PhantomJS as per the _build_ instructions, you should use the produced binary in the `bin` directory. You should not download 2.1.0 binary.

Please note that you could use the provided binaries for the forked version of PhantomJS as documented in the _install_ section. That's preferable over to build PhantomJS yourself if a binary version if provided for your target platform.

**Comment by jensgro** [comment]
Okay, then the path was the problem. I wrote in my terminal 
`phantomjs/bin/phantomjs decktape.js shower <url> name.pdf`  and it started to work. Because I use Shower2 it halted very fast, but your script seems to be working. Only the path should be actualised in the documentation.

Thanks for your help. I hope for the new Shower 2 version.

**Comment by astefanutti** [comment]
@jensgro just a heads-up that Shower 2 is now supported since @328e4438189c2f9a12dcc548a4a9b8557bdb59b5.
