### ISSUE TITLE
remark.js printing issue if slides are passed to remark.create as a separate file

### ISSUE THREAD

**Issue by anaderi** [astefanutti/decktape#48]
error 

1. wget https://gnab.github.io/remark/\#1
2. download remark js locally
3. jekyll serve
4. open http://localhost:4000 works nicely
5. ~/git/decktape/bin/phantomjs  ~/git/decktape/decktape.js remark   http://127.0.0.1:4000/ --slides 1-5 remark.pdf
```
Loading page http://127.0.0.1:4000/ ...
Loading page finished with status: success
Remark JS DeckTape plugin activated
Printing slide #1       ( 1/19) ...      Regenerating: 1 file(s) changed at 2016-05-05 02:58:32 ...done in 0.003893 seconds.
Printing slide #4       ( 4/19) ...      Regenerating: 1 file(s) changed at 2016-05-05 02:58:36 ...done in 0.00326 seconds.
Printing slide #5       ( 5/19) ...
Printed 5 slides
```
6. move contents of     <textarea id="source">    </textarea> into body.md and add argument to remark.create           `sourceUrl: 'body.md',`
7. restart jekyll, http://localhost:4000 still works nicely
8. but `~/git/decktape/bin/phantomjs  ~/git/decktape/decktape.js remark   http://127.0.0.1:4000/ --slides 1-5 remark.pdf` produces just empty slide:
```
➜  ~/git/decktape/bin/phantomjs  ~/git/decktape/decktape.js remark   http://127.0.0.1:4000/ --slides 1-5 remark.pdf
Loading page http://127.0.0.1:4000/ ...
Loading page finished with status: success
Remark JS DeckTape plugin activated
Printing slide #1       (1/1) ...
Printed 1 slides
➜  bug       Regenerating: 1
```
What am I doing wrong?

**Comment by astefanutti** [comment]
I suspect this is related to #12 and the root cause issue ariya/phantomjs#13908. The fix for this issue has already been integrated into DeckTape `master` branch.

Would you be able to build the latest version of DeckTape / PhantomJS as documented in the build section and give it a try?

**Comment by anaderi** [comment]
@astefanutti , I've used prebuilt phantomjs for Mac OS X. will try to rebuild it by hand, but since #12 and  ariya/phantomjs#13908 seems to be pretty old, I'd expect that prebuilt binary should have it already. will try to rebuild it anyway (although it seems to depend on plenty of various stuff and may take some time)

**Comment by astefanutti** [comment]
@anaderi unfortunately I haven't uploaded pre-built binaries for a while so that ariya/phantomjs#13908 isn't included in them. Let me re-upload Mac OS X binary that I have so that you can give it a try and save you the hassle of rebuilding it locally.

**Comment by anaderi** [comment]
@astefanutti ok, let me know as you upload it, since building didn't fly out of the box )

**Comment by astefanutti** [comment]
@anaderi I've just uploaded up-to-date binary for Mac OS X @048dc67a8d2744e5abf639309862d567566256ea. Let me know if that fixes the issue.

**Comment by anaderi** [comment]
Thanks, woks perfectly now!
