### ISSUE TITLE
Printing MathJax formulae

### ISSUE THREAD

**Issue by anaderi** [astefanutti/decktape#50]
For rendering formulas I use MathJax:

```javascript
      MathJax.Hub.Config({
          tex2jax: {
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
            inlineMath: [['$','$'], ['\\(','\\)']],
            extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js"]
          }
      });
      MathJax.Hub.Queue(function() {
          $(MathJax.Hub.getAllJax()).map(function(index, elem) {
              return(elem.SourceElement());
          }).parent().addClass('has-jax');
      });
      MathJax.Hub.Configured();
```

but the formula `\int_{\Delta} \dfrac{\sin x}{\cos y} dz` rendered in HTML:

![html](https://picpig.com/dobdh008vk.png)

 and in PDF:

![pdf](https://picpig.com/iebmtc1n0u.png) 

it looks a bit different. 
Is there a simple way to fix it?

**Comment by anaderi** [comment]
maybe helpful: https://gist.github.com/pkra/52391c345ae48613e5e0

**Comment by astefanutti** [comment]
I've just pushed @eb0e3c63c91484b9d350175d19bd07026e68a924 which waits for the `End` MathJax `StartupHook` before exporting the slides.

Unfortunately, the type setting is still incorrect in the example that I've tested so far (the `math.html` example from reveal.js source). Even the example from https://gist.github.com/pkra/52391c345ae48613e5e0 fails to render properly with the latest version of PhantomJS. So I suspect this is more a PhantomJS issue with MathJax typeset functionality though maybe you could give that first commit a try to have your opinion on this.

**Comment by anaderi** [comment]
hmm, the problem was in lack of my knowledge reading MathJax docs. one more option to `MathJax.Hub.Config` fixes that problem:
```
"HTML-CSS": { availableFonts: ["TeX"] }
```
so probably without waiting till `End` we could use decktape just increasing timeout in `--pause` option.
Upside of this investigation are that
- now I can remove that pause
- I've learned to use KaTeX that works also well with remark & decktape (and is know to be a bit faster)
