### ISSUE TITLE
decktape, docker and network issue

### ISSUE THREAD

**Issue by oupala** [astefanutti/decktape#51]
I'm trying to use the decktape docker container, but I'm having some trouble using the container and letting it access the network.

Here is the result of my command:

```bash
>docker run --rm -v `pwd`:/pwd astefanutti/decktape http://remarkjs.com/ /pwd/export.pdf
Loading page http://remarkjs.com/ ...
+- Unable to load resource from URL: http://remarkjs.com/
|_ Error code: 4
|_ Description: Socket operation timed out
Loading page finished with status: fail
Unable to load the address: http://remarkjs.com/
```

I'm pretty sure that I'm doing something wrong as the docker container must have been tested by someone else.

Can anyone help me?

**Comment by oupala** [comment]
The same export works well while using the raw code instead of the docker container:

```bash
$ npm start http://remarkjs.com/ /tmp/export.pdf

> decktape@1.0.0 start /home/user/decktape
> ./bin/phantomjs decktape.js "http://remarkjs.com/" "/tmp/export.pdf"

Loading page http://remarkjs.com/ ...
Loading page finished with status: success
Remark JS DeckTape plugin activated
Printing slide #19      (19/19) ...
Printed 19 slides
```

That makes me think that it is a docker related issue, due to my lack of knowledge with docker.

**Comment by astefanutti** [comment]
I've double-checked by running the command below with a typical / pristine Docker installation and I confirm this works fine:
```
docker run --rm -v `pwd`:/pwd astefanutti/decktape http://remarkjs.com/ /pwd/export.pdf
```
I can suggest you try to isolate your problem by running a container process with a TTY allocated based on a typical image (`docker run -it`) and troubleshooting your network issue.

**Comment by oupala** [comment]
I followed your advice and it has paid off.

I just had to add some environment variables in order to use my proxy server:
```bash
docker run -e "http_proxy=http://proxy:8080/" --rm -v `pwd`:/pwd  astefanutti/decktape http://remarkjs.com/ /pwd/export.pdf
```

It does now work like a charm.

Thanks a lot @astefanutti for your help!

**Comment by astefanutti** [comment]
@oupala glad to hear it worked! Thanks for the feedback!

**Comment by oupala** [comment]
There is a small detail that break the user experience: we have to specify a path for the generated file (here: `/pwd/export.pdf`) even if we want to file to be saved on the current directory on the host.

Is there a way to prevent that and to specify only `export.pdf` on the command line?

I tried to bind `/` (`-v 'pwd':/`) but I had an error:

```bash
docker: Invalid bind mount: destination can't be '/'. See 'docker run --help'.
```

**Comment by oupala** [comment]
I also tried with http://lab.hakim.se/reveal-js and phantomjs seems to stay stuck.

Do you know why?
