### ISSUE TITLE
SVG images cause background to have vertical offset

### ISSUE THREAD

**Issue by rbirkby** [astefanutti/decktape#52]
Adding an SVG image to markdown as an image causes any background image to be positioned incorrectly.

```markdown
background-image: url(images/background.png)

# Slide with SVG

The background has a vertical offset

![](images/drawing.svg)
```

Only tested with remarkjs on Windows. DeckTape dfc4b772, 

## Example output

Without SVG:

![image](https://cloud.githubusercontent.com/assets/203034/15674545/459442fe-2735-11e6-9c6d-68d9aaf7d1f3.png)

With SVG:

![image](https://cloud.githubusercontent.com/assets/203034/15674554/541ccb0c-2735-11e6-9754-5f4244d8dc76.png)

## Testcase

https://github.com/rbirkby/DeckTapeIssue

**Comment by astefanutti** [comment]
I've opened the test case in Safari (WebKit engine on which is based PhantomJS) and the issue reproduces. Adjusting the size of the SVG, in such way that the SVG does not overflow the slide container, leads to having the background image positioned correctly

It appears that, when inspecting the `div` with the class `remark-slide-content` on slide 2, it has the `background-position: 50% 0px;`  style when rendered with Chrome while the attribute is missing when rendered in Safari.

Adding `background-position: 50% 0px;` actually fixes the rendering issue in WebKit, which is likely to fix the issue with DeckTape.

I'm not familiar with remark.js internals though I suspect this is an issue on their side. As a possible work-around, It looks like there is a way for users to override that with grab/remark@d0332282a6f9f5be7f41c424b8055af6f6e93d92.

**Comment by astefanutti** [comment]
Let's follow this up in gnab/remark#339 and reopen it if needed.
