### ISSUE TITLE
PhantomJS precompiled binary for Ubuntu 16.04 x86-64.

### ISSUE THREAD

**Issue by onetapbeyond** [astefanutti/decktape#56]
Currently there are precompiled binaries for Win, OSX, CentOS and Debian. But not for Ubuntu. So I've built one for Ubuntu 16.04. If I give you a link where you can pull this new Ubuntu binary would you be interested in making this binary available on http://astefanutti.github.io/decktape/downloads?

**Comment by astefanutti** [comment]
@onetapbeyond sure. That'd be even better if you create a PR to upload the binary in the `gh-pages` branch (and a separate one to update the README). Besides, please make sure to compress the binary with UPX.

**Comment by onetapbeyond** [comment]
No problem. Submitted PR #58 and #59.
