### ISSUE TITLE
Docker export and working directory

### ISSUE THREAD

**Issue by oupala** [astefanutti/decktape#63]
There is a small detail that break the user experience of docker usage: we have to specify a path for the generated file (here: `/pwd/export.pdf`) even if we want to file to be saved on the current directory on the host.

The current command looks like:

```bash
docker run --rm -v `pwd`:/pwd  astefanutti/decktape http://remarkjs.com/ /pwd/export.pdf
```

Is there a way to prevent that and to specify only `export.pdf` on the command line and to export the file to the current directory (`pwd`) on the host?

```bash
docker run --rm -v `pwd`:/pwd  astefanutti/decktape http://remarkjs.com/ export.pdf
```

I tried to bind `/` (`-v 'pwd':/`) but I had an error:

```bash
docker: Invalid bind mount: destination can't be '/'. See 'docker run --help'.
```

**Comment by astefanutti** [comment]
The only way to achieve this that I know of is to run:

    docker run --rm -v `pwd`:/pwd -w /pwd astefanutti/decktape http://remarkjs.com/ export.pdf

This will execute in the specified working directory `/pwd`, which is mounted to the current directory.

As documented in [Mount a host directory as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume):

> The host directory is, by its nature, host-dependent. For this reason, you can’t mount a host directory from `Dockerfile` because built images should be portable. A host directory wouldn’t be available on all potential hosts.

So this can be defined in DeckTape `Dockerfile` and has to be specified on the command line by the end-user.

**Comment by oupala** [comment]
@astefanutti, you're solution would be great!

Can you add the `WORKDIR` in the Dockerfile or do you prefer that I create a pull request?

**Comment by astefanutti** [comment]
@oupala, we could declare a default `/slides` working directory in the `Dockerfile`. The `ENTRYPOINT` would have to be updated to reference the absolute path of the `decktape.js` script.

You're welcome to create a PR. That'd be great if you could update the Docker instructions in the README file as well 😉.

**Comment by oupala** [comment]
I've just created a pull request #64. I let you rebuild the Dockerfile when the pull request is merged (unless this is done automatically on a `git push` event).

In the meantime, you can already benefit the way of using the docker image by creating the following alias in your `.bash_aliases` file:

```bash
alias decktape='docker run --rm -v `pwd`:/pwd -w /pwd astefanutti/decktape'
```

and then call the docker container by the following command:

```bash
decktape http://remarkjs.com/ export.pdf
```

**Comment by astefanutti** [comment]
Merged @f913091b606faa9f20719b207b58ce8f85b69c06. Thanks!

**Comment by astefanutti** [comment]
The Docker image has just been built successfully on DockerHub.

**Comment by oupala** [comment]
It works like a charm!
