### ISSUE TITLE
"SSL handshake failed" when loading fonts from Google Fonts via HTTPS

### ISSUE THREAD

**Issue by szpak** [astefanutti/decktape#68]
Decktape fails to get font from Google Fonts if HTTPS is used:

```
+- Unable to load resource from URL:
https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,700,700i&subset=latin-ext
|_ Error code: 6
|_ Description: SSL handshake failed
```

Sample font inclusion (fails also with `@import`):
```
<link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,700,700i&subset=latin-ext" rel="stylesheet">
```

Tested with 1.0.0 as a Docker image (as a side effect of #67).

**Comment by astefanutti** [comment]
Thanks for the report! that should be fixed in the latest version of the `astefanutti/decktape` Docker image.
