### ISSUE TITLE
Mac OS binary does not work on OS X Sierra

### ISSUE THREAD

**Issue by MaxKemman** [astefanutti/decktape#71]
I build my slides with flowtime.js, and then convert to pdf using the command:
`.phantomjs decktape.js flowtime "/Users/name/etc/doc.html" "/Users/name/etc/doc.pdf" --size=1920x1080`

This worked perfectly, but as of today I get the message "**Killed: 9**". I updated to OSX 10.12 earlier this week so that's probably related. I've updated to the latest version of decktape

**Comment by astefanutti** [comment]
It looks like it is caused by upx/upx#4. I'll update the Mac OS binary ASAP.

**Comment by astefanutti** [comment]
I've just updated the Mac OS X binary in the [`1.0.0`](https://github.com/astefanutti/decktape/releases/tag/v1.0.0) release (it's simpler / faster that way).

It can be retrieved from: https://github.com/astefanutti/decktape/releases/download/v1.0.0/phantomjs-osx-cocoa-x86-64

Could you give it a try as I haven't upgraded to Sierra?

**Comment by MaxKemman** [comment]
I installed Decktape 1.0.0 again with the new UPX patch, and now everything works again. Many thanks!

**Comment by astefanutti** [comment]
@MaxKemman great! Thanks for the feedback and the report.

**Comment by darribas** [comment]
I've had a similar experience when trying to run decktape after the upgrade to Sierra. I see the following:

```
dh073191:decktape_darribas dani$ ./bin/phantomjs decktape.js -h
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/dani/code/decktape_darribas/./bin/phantomjs
  Reason: image not found
Abort trap: 6
dh073191:decktape_darribas dani$
```

This is with the `master` version of `decktape` (freshly checked out of Github) and using the phantomjs link above in this thread (the one with the `UPX` patch).

Thanks very much!!!

It seems to be related to `openssl` but, beyond that, I can't figure out how to make it work. Has anyone had a similar experience?

**Comment by astefanutti** [comment]
@darribas I haven't upgraded myself to Sierra yet and haven't heard anything like this error before. You may want to search PhantomJS issue tracker in case somebody else has faced a similar issue. On my side I'll upgrade ASAP and give it a try.

**Comment by darribas** [comment]
Thanks very much for the answer @astefanutti. I've worked around the issue for now using the docker image, which seems to work just fine. However, if you run into this or see of anyone running into it, I'd very much prefer to keep using the native approach. It does seem to be related to `phantomjs` rather than to `decktape`, but not sure if it has to do with your fork of it or with all versions. Thanks anyway!

**Comment by darribas** [comment]
In case this is of help for anyone in a similar situation, I fixed this by installing Homebrew and running:

```
brew install openssl
```

Then worked like a charm :-) I do not recall having to install that on El Capitan though.

**Comment by pboesu** [comment]
Just for the record: I had the same `libssl` error message as darribas on a OSX Yosemite machine running MacPorts.
`dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

In my case, adding a symlink from the presumed Homebrew path `/usr/local/opt/openssl/lib` to the corresponding MacPorts path  `/opt/local/lib/` fixed the issue.

**Comment by SJern** [comment]
`export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH`

Also worked for me
