### ISSUE TITLE
MathJax font rendering inconsistencies across OSX and Linux.

### ISSUE THREAD

**Issue by gitpitch** [astefanutti/decktape#72]
When testing the decktape output generated when rendering MathJax formulas within GitPitch presentations (built on reveal.js) I am seeing significant differences in the font rendering between OSX and Linux/Ubuntu 16.04.

Here is a screenshot of the PDF output generated on OSX:

![mathjax-osx](https://cloud.githubusercontent.com/assets/19169584/19144777/af9f1f70-8bd5-11e6-920c-14ce1de16853.png) 

Here is a screenshot of the PDF output generated on Ubuntu:

![mathjax-ubuntu](https://cloud.githubusercontent.com/assets/19169584/19144810/d49d72b8-8bd5-11e6-94a0-5c4203ee4199.png)
 
These outputs were generated using the same slideshow input. The OSX output appears to be using a high quality font compared to the rather plain Ubuntu output.

All output show here was generated using decktape 1.0.0.

Should I expect to see consistent rendering across OSX and Linux? If not, what steps can I take, if any, to improve the fonts used by decktape when generating MathJax output in PDFs on my Linux deployment?

A sample GitPitch presentation rendered to PDF by decktape on Linux can be found [here](https://gitpitch.com/gitpitch/feature-demo/mathjax). Just click `Print` option at the bottom of the page. Thanks for any help you can provide.

**Comment by gitpitch** [comment]
@astefanutti do you know offhand if the problem I'm reporting here looks like the same problem you were addressing in issue #3 that was closed out in your recent 1.0.0 release?

I've tried both the pre-built 1.0.0 binary and a binary I built myself from `astefanutti/phantomjs.git` for Ubuntu 16.04 and in both cases I see the same kind of output as described in my original feedback.

As previously noted, the same presentation is rendered to PDF perfectly on OSX.

**Comment by astefanutti** [comment]
@gitpitch It's very likely to be a different problem than in #3.

A similar issue has already been noticed a while ago in #50. It seems that configuring the type-setting with `"HTML-CSS": { availableFonts: ["TeX"] }` fixed the issue.

However, this might be a different issue as it wasn't explicitly OS dependent. Font selection vary from one OS to another. A first step would be to make sure that you have the expected font installed on your OS. Then we'll have to investigate why that font isn't selected.

**Comment by gitpitch** [comment]
@astefanutti is there some way I can enable debug or otherwise to find out (1) what fonts decktape is looking for and (2) what fonts decktape ends up using for a given pdf job?

**Comment by astefanutti** [comment]
@gitpitch unfortunately no straightforward method that I would know of. On Linux OS, it may be that Qt delegates to the OS the font selection. So a way to get more insight would be to run `fc-match` (with the `fontconfig` package installed). A first manual check would be to verify that the font that should be used in formula is installed on your OS, or to check that it renders as expected in the browser.

**Comment by gitpitch** [comment]
Having ensured the MathJax fonts were available and verified by `fc-match` I still could not convince `decktape` on my Ubuntu box to use these fonts when rendering `mathjax` formulas. As noted previously, on OSX it these fonts are used as expected. Not sure what else I can do at this point. The issue is probably specific to my local env as I've not found evidence of this problem reported elsewhere. Closing issue.
