### ISSUE TITLE
Last RISE sub-slides are not included

### ISSUE THREAD

**Issue by akaihola** [astefanutti/decktape#73]
In my Jupyter Notebook slides which have been created using RISE, I'm using both the "Slide" and "Sub-Slide" slide types. My last slide is `#/slide-8-0` with a sub-slide `#/slide-8-1`. Decktape fails to include the last sub-slide. If I change its type to "Sub-Slide", it gets included.

If I open the original presentation interactively in the browser, jump to the `#/slide-8-0` slide and execute this in the JavaScript console, I get "null" instead of `["SECTION"]`:

```
> Reveal.getCurrentSlide().parentNode.nextElementSibling.nodeName.match(/section/i);
null
```

Probably that test in `hasNextSlide()` would need to be tweaked to detect trailing sub-slides as well.

**Comment by astefanutti** [comment]
It's been fixed with 64a163a9889797c9de410aee1c3f874a6f7aa0d3.
