### ISSUE TITLE
RISE fragments are not included at all

### ISSUE THREAD

**Issue by akaihola** [astefanutti/decktape#74]
If I render my Jupyter Notebook / RISE presentation, any cells marked as "Fragment" are omitted from the PDF.

I couldn't find a configuration option in reveal.js to force all fragments to be displayed immediately. The `fragments: false` option used in the RISE plugin seems to disable displaying all fragments also when used in an interactive browser (by adding `?fragments=false` to the URL).

My work-around is to turn fragments into normal cells before rendering, but that's of course not optimal.

**Comment by astefanutti** [comment]
It should be fixed with 589b69a23f6864900375139d590335e8aa6d11f0.
