### ISSUE TITLE
Bespoke plugin doesn't work

### ISSUE THREAD

**Issue by hasalex** [astefanutti/decktape#75]
When I run decktape on Bespoke slides, such as the "Welcome our new ES5 Overloards" example, I have the following error message:

> Error: Unable to activate the Bespoke.js DeckTape plugin for the address: http://mikemaccana.github.io/rejectjs2013

Here is my command line:
`./phantomjs decktape.js bespoke http://mikemaccana.github.io/rejectjs2013 slides.pdf`

I've also tested locally with my own slidedeck, and it fails too.

Note : it's working fine with the other examples.

**Comment by hasalex** [comment]
I've found my mistake : I had to add the **bespoke-extern** module.

Now my local example works. The output is not really as nice as what I was expecting, but now I have an output.

**Comment by astefanutti** [comment]
@hasalex an alternative is to use the _generic_ plugin. Do not hesitate to report any issue that you face for the rendering.

**Comment by hasalex** [comment]
Thanks, I'll investigate further. Looks like a problem with flexbox. I'll report on an other issue if I'm stuck with it.

**Comment by astefanutti** [comment]
Ah flexbox isn't supported by PhantomJS yet. There is a major migration to the latest WebKit version going on that'll bring support for it among many other things.

**Comment by hasalex** [comment]
OK. Thanks for the information.
