### ISSUE TITLE
Windows XP PhantomJS binary

### ISSUE THREAD

**Issue by zhiying8710** [astefanutti/decktape#80]
can u build a xp version, thx, my program need it,  i've found every where but no luck

**Comment by astefanutti** [comment]
Ah the Windows binary has been built on Windows 7 so I guess PhantomJS needs to be built on XP for it to work. I'll need to find a XP box.

**Comment by astefanutti** [comment]
Apparently, there is a way to configure MSVC to target XP:
- http://doc.qt.io/qt-5/windows-issues.html#targeting-xp-with-visual-studio-2012-and-later
- https://blogs.msdn.microsoft.com/vcblog/2012/10/08/windows-xp-targeting-with-c-in-visual-studio-2012/

So hopefully it won't be needed to have a XP box. I'll give it a try next time I build the Windows PhantomJS binary.

**Comment by zhiying8710** [comment]
ok, thx, i'll try it!

**Comment by astefanutti** [comment]
DeckTape 2.x now uses Node and Chrome. I'm afraid both Node and Chrome have dropped support for Windows XP though you can still give it a try as it's unlikely I build a new version of the PhantomJS binary as PhantomJS has been abandoned.
