### ISSUE TITLE
Problem executing .phantomjs

### ISSUE THREAD

**Issue by pachevalier** [astefanutti/decktape#81]
I've tried to install decktape using the following instructions : https://github.com/astefanutti/decktape/releases/tag/v1.0.0

When I try to execute : 

    $ ./phantomjs/ decktape.js -h

I've got an error which tells me : 

    bash: ./phantomjs/ : is a directory

Any explanation ?

**Comment by astefanutti** [comment]
You should remove the slash, i.e.:

    $ ./phantomjs decktape.js -h

instead of:

    $ ./phantomjs/ decktape.js -h

**Comment by pachevalier** [comment]
I've got the same error. 

I run Debian testing.

**Comment by astefanutti** [comment]
Make sure the `phantomjs` binary is correctly downloaded and executable. You may want to run `ls -al .` in the installation directory.

**Comment by pachevalier** [comment]
OK I've just reinstalled everything and it seems to work

**Comment by astefanutti** [comment]
I'm glad it worked. Let me know if you face any other issues.
