### ISSUE TITLE
Merge phantomjs's fork changes into official repo?

### ISSUE THREAD

**Issue by sinedied** [astefanutti/decktape#83]
It may be a dumb question, but why not propose a PR to merge the specific changes made to PDF export into the main phantomjs repo?

If accepted, this would simplify greatly the installation process and usage of this tool :)

**Comment by astefanutti** [comment]
That's definitely something we want to do. I've documented the current status of getting DeckTape bits back into PhantomJS here: https://github.com/astefanutti/decktape#status.

I'll be working ASAP on the upgrade to PhantomJS 2.5 that brings support for CSS3, ES6 and other goodies with the rebase to latest WebKit. Then I'll work on merging the remaining requirements upstream.

Let me close this as this answers your question and I'll keep you posted ASAP.

**Comment by sinedied** [comment]
Any update on this? This would also allow #53

**Comment by astefanutti** [comment]
I'm still waiting a bit for PhantomJS 2.5 beta to stabilise a bit. Then I plan to do the upgrade and merge the DeckTape bits into it. That's something I definitely want to do ASAP.
