### ISSUE TITLE
Relatively large PDF file

### ISSUE THREAD

**Issue by szpak** [astefanutti/decktape#87]
PDF of my presentation with ~120 slides (just text and code almost without images - code has font defined correctly and it is not rendered as a bitmap) created with DeckTape 1.0.0 takes ~3,5MB. Almost the same presentation generated some time ago using Chrome takes ~800KB. The interesting is that both files compressed with 7z takes almost the same amount of space.

I plan to dig a little bit what element in my presentation bumps the file size (I already gained ~500KB by removing opacity style from my footer), but maybe there is already a known solution (such as enabling an internal PDF compression in QT producer)?

**Comment by astefanutti** [comment]
I haven't look that much into QT PDF compression tuning yet. From my experience, the usual cases that tend to contribute to larger file size is:
- Opacity < 1 that leads to text being rendered as bitmap; my assumption is that QT does not leverage PDF transparency yet and falls back to bitmap rendering;
- Text being rendered as vector primitives instead of embedded font glyphs; that happens when font embedding does not happen as expected for some reasons;
- A background image that repeats in each slide and that happens to be written multiple times in the file.

**Comment by szpak** [comment]
I already eliminated opacity (by just using gray font instead of black which was enough in my case) and font glyphs in code (by defining font for code explicitly - not just sans-sherif). I have a logo on the every slide - I will check it.

**Comment by astefanutti** [comment]
@szpak I've been working on improving output PDF size in DeckTape 2.x. Could you test with latest `2.3.0` version and check what's the result?

**Comment by szpak** [comment]
@astefanutti I haven't got a chance to test 2.x, but I will try to give it a shot shortly.

**Comment by szpak** [comment]
I checked the latest docker image (image was updated 3 days ago, so it could be 2.3.0, however, maybe Decktape in a Docker could display its version?). My other 160 slides with 1.x had 4,7MB as PDF. In 2.3.0 it's slightly better - 4,5MB. I tried to remove repeatable logo (completely), but it only reduced the size to 4,4MB. Source code is properly rendered as text.

Next time working on slides I will try to identify which kind of slides generates more size than others.

**Comment by astefanutti** [comment]
@szpak thanks a lot for the feedback. You can run `decktape version` to get the current version. I plan to work on font definitions consolidation ASAP which I think should possibly reduce the output size. Let me know your results on your side.

**Comment by astefanutti** [comment]
I've just implemented fonts consolidation in version `2.4.0`. This and duplicate images consolidation is pretty much what I can think of to improve output PDF size. I'll close this one but feel free to open a new issue with specific contributors to file size so that I can try addressing them.

**Comment by szpak** [comment]
As late feedback to that topic, by the way of the new presentation I also regenerated the old one. 71 slides, some pictures and 2 logos repeating every page. The result is very good. The overall size decreased from 2,1MB to 1MB. Nice!

The old PDF was generated with the latest Decktape available as of April 2017. The new one is with 2.8.0.

Btw, there could information in the PDF metadata that it was created with Decktape X.X.X. Currently there is only Qt alosne set as a producer.
