### ISSUE TITLE
Add an option to export each slide as an image

### ISSUE THREAD

**Issue by mojavelinux** [astefanutti/decktape#9]
Add an option that exports each slide as an image as it is creating the PDF. This can be accomplished by calling the `page.render` method before the `printer.printPage` call.

The benefit of exporting each slide to an image is that those images can then be used independently to create other documents, such as a handout that includes slide notes under each slide image.

Currently, it seems that only raster images are supported (png, jpg). Ideally, it would be possible to also have slides exported as SVGs (for all the same benefits, and more, that decktape provides by creating a PDF).

**Comment by hadim** [comment]
In fact `page.render(page_0.pdf)` should work. See http://phantomjs.org/api/webpage/method/render.html.

**Comment by mojavelinux** [comment]
Actually, that's different. It renders the unstyled slide to PDF.

Regardless, it doesn't help to have more PDF files. If we wanted that, we
could simply split the PDF file apart. What we need are images that can be
used independently, like in a web page, gallery or another PDF (but
embedded).

**Comment by mojavelinux** [comment]
Here's the code that we'd need once the option is enabled.

```js
imageFileName = printer.outputFileName.replace(".pdf", ("_" + plugin.currentSlide + ".png"));
page.render(imageFileName);
```

**Comment by astefanutti** [comment]
I've got it working. Just need to polish it a bit and I'll push it.

**Comment by mojavelinux** [comment]
Super!

**Comment by mojavelinux** [comment]
Nice! Thanks!

**Comment by astefanutti** [comment]
@mojavelinux let me know if that works for you.

**Comment by mojavelinux** [comment]
Works great!

I have two suggestions:

1. I find the order of arguments to be odd. Most commands take options before the filename(s). However, decktape.js puts all options at the end of the command.

2. It might be a good idea to make the filename length of each screenshot the same by padding the number with zeros (e.g., slides_01_x1.png). This helps with sorting.
