### ISSUE TITLE
SVG text is extremely tiny 

### ISSUE THREAD

**Issue by schlichtanders** [astefanutti/decktape#90]
When using a svg within a reveal.js presentation, the size of the text is way too small
(you might even think there is no text)
![decktape svg tiny text](https://cloud.githubusercontent.com/assets/4255480/24297072/b2914e46-10a1-11e7-940c-bc55cdbfab1f.PNG)

The example svg I got from https://demos.explosion.ai/displacy/ where at the top right there is an export button which asks you to save a ``displacy.svg`` file. I would attach it here, however I cannot see any attachment feature, so please download it yourself.

Any ideas why this behaviour happens and how to fix it?

**Comment by astefanutti** [comment]
Should be fixed in version `2.0.1` that uses headless Chrome. Let me know if you still face this issue.
