### ISSUE TITLE
MathJax rendering is indeterministic

### ISSUE THREAD

**Issue by schlichtanders** [astefanutti/decktape#91]
I am using rise plugin (builds upon reveal.js). Running `phantomjs decktape.js rise <URL> <OUTPUT.PDF>` several times without any changes inbetween results in different rendering mathjax formulas each

### some example screenshots
first run:
![decktape formula 1](https://cloud.githubusercontent.com/assets/4255480/24300841/0b7c4964-10ae-11e7-8178-866c485ff3f4.PNG)
second run:
![decktape formula 2](https://cloud.githubusercontent.com/assets/4255480/24300844/0dc33f0c-10ae-11e7-8477-9574e620978a.PNG)
third run:
![decktape formula 3](https://cloud.githubusercontent.com/assets/4255480/24300846/0f0a8ad2-10ae-11e7-8dd3-79d90a28fb22.PNG)

**Comment by astefanutti** [comment]
It may be due to Reveal loading the MathJax extension asynchronously, so adding the `--load-pause` option may help guaranteeing that everything gets loaded correctly. It is detailed in https://github.com/astefanutti/decktape/issues/76#issuecomment-275919992.

**Comment by schlichtanders** [comment]
I added ``--load-pause=20000``

unfortunately, the first run it showed the same as the "first run" above

luckily all the other 4 runs I tested showed the most desirable output which above was "second run"

so it seemed to have worked kind of - thanks a lot for your quick response!

**Comment by astefanutti** [comment]
Great. Let me know you results. I drafted proper support for MathJax loading a while back  @eb0e3c63c91484b9d350175d19bd07026e68a924 and I'd be interested with your tests so that I consider pushing that work further or not.

**Comment by astefanutti** [comment]
Should be fixed with DeckTape 2.x.

Here is the Reveal math example exported using 2.2.2: [test.pdf](https://github.com/astefanutti/decktape/files/1298839/test.pdf).
