### ISSUE TITLE
Copy/paste of preformatted block from PDF breaks formatting

### ISSUE THREAD

**Issue by utdrmac** [astefanutti/decktape#95]
See attached RemarkJS source code which contains 2 slides, the first one of which has some block code. This renders OK in the PDF with exception of issues raised in #67. When you attempt to select and copy this block code, and paste into a text editor/terminal, the formatting is completely lost. This is the result of copy/paste from slide 1 in this PDF:

```
wsrep_provider wsrep_cluster_name wsrep_cluster_address wsrep_node_name wsrep_node_address wsrep_sst_auth
= ROW
= /usr/lib64/libgalera_smm.so = mycluster
= gcomm://node1,node2,node3 = node3
= 192.168.70.4 = sst:secret
innodb_autoinc_lock_mode = 2 innodb_locks_unsafe_for_binlog = ON
```

[test.pdf](https://github.com/astefanutti/decktape/files/955727/test.pdf)
[test_html.txt](https://github.com/astefanutti/decktape/files/955729/test_html.txt)

**Comment by astefanutti** [comment]
I've just tried to reproduce and it seems the result depends on the PDF reader used, e.g., with Acrobat Reader and Chrome (pdf.js), I get:

```
wsrep_provider = /usr/lib64/libgalera_smm.so
wsrep_cluster_name = mycluster
wsrep_cluster_address = gcomm://node1,node2,node3
wsrep_node_name = node3
wsrep_node_address = 192.168.70.4
wsrep_sst_auth = sst:secret
innodb_autoinc_lock_mode = 2
innodb_locks_unsafe_for_binlog = ON
```

And with Mac OS Preview:

```
wsrep_provider wsrep_cluster_name wsrep_cluster_address wsrep_node_name wsrep_node_address wsrep_sst_auth
innodb_autoinc_lock_mode innodb_locks_unsafe_for_binlog
= ROW
= /usr/lib64/libgalera_smm.so = mycluster
= gcomm://node1,node2,node3
= node3
= 192.168.70.4
= sst:secret
= 2 = ON
```

Out of curiosity, what PDF reader are you using?

I've tried printing to PDF the presentation directly with Chrome and I get the following result with Acrobat Reader:

```
wsrep_provider = /usr/lib64/libgalera_smm.so
wsrep_cluster_name = mycluster
wsrep_cluster_address = gcomm://node1,node2,node3
wsrep_node_name = node3
wsrep_node_address = 192.168.70.4
wsrep_sst_auth = sst:secret
innodb_autoinc_lock_mode = 2
innodb_locks_unsafe_for_binlog = ON
```
 
I could dig into how exactly the code block gets encoded in the PDF file though I'd tend to think it may depend on the reader rather than the encoder based on the above results.

**Comment by utdrmac** [comment]
Ah. I should have mentioned that. I was using MacOS Preview, as that is the default PDF viewer. I don't have Acrobat Reader. I just opened my test.pdf inside Chrome and it copied fine. I guess that'll be a caveat. *shrug*

**Comment by astefanutti** [comment]
I'm glad it works for you using Chrome. MacOS preview is a general purpose viewer so I can imagine it's not perfectly tailored for PDF. Anyway if other people mention that issue, I may find a place to add that kind of caveat. In the meantime, let me close that issue and do not hesitate to reopen if you face any other problem.
