### ISSUE TITLE
Mention decktapify in the docs

### ISSUE THREAD

**Issue by eduardsi** [astefanutti/decktape#96]
Hello! 

I have developed a free HTTP service for exporting HTML5 presentations to PDF. It uses a fantastic Decktape under the hood. Please consider mentioning it in the docs – https://github.com/devternity/decktapify

**Comment by astefanutti** [comment]
Thanks for the heads-up!

I'll add a dedicated section to the README to list the available online services based on DeckTape.

**Comment by m1guelpf** [comment]
@astefanutti It seems like the code has been removed... could you provide the code of the original decktapify repo?

**Comment by astefanutti** [comment]
@m1guelpf https://github.com/devternity/decktapify seems accessible.

**Comment by m1guelpf** [comment]
@astefanutti Redirects to sponsorify, that seems to be another thing.

**Comment by eduardsi** [comment]
Yes, the project has been morphed into something different and is not relevant for general audience anymore

**Comment by m1guelpf** [comment]
@eduardsi Do you have the original project's source somewhere?

**Comment by eduardsi** [comment]
The whole idea that Decktape was running as a free web service (lambda). There is not that much code apart from simple plumbing. Unfortunately, the original project was replaced with the code specific to [DevTernity](https://devternity.com) conference docs.

**Comment by astefanutti** [comment]
Given these new highlights, plus that is it not based on DeckTape 2.x, I'm inclined to close this. I'm planning to work DeckTape online ASAP.
