### ISSUE TITLE
libssl.1.0.0.dylib error on Mac OS with latest forked PhantomJS binary

### ISSUE THREAD

**Issue by lowescott** [astefanutti/decktape#99]
Hi all, I'm running into this error on both macOS Sierra (10.12.5) as well as OS X El Capitan (10.11.6):

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /opt/decktape/phantomjs
  Reason: image not found
make: *** [slides] Trace/BPT trap: 5
```

This looks similar to the error reported in #71, but happening on both Sierra and El Capitan. Is there any solution **other** than using `brew` to install a custom OpenSSL version?

**Comment by astefanutti** [comment]
It may be due to the fact that the binary build linked against the OpenSSL libraries installed via Homebrew as opposed to the system libraries.

I could try re-building the binary but I'm afraid PhantomJS requires OpenSSL 1.x API which may not be compatible with version 0.9.x, that seems to be the version shipping with Mac OS X:

    /usr/lib/libssl.dylib@ -> libssl.0.9.8.dylib

It's probably the reason OpenSSL via Homebrew or via MacPorts is a documented requirement for the PhantomJS build on Mac OS X.

So until we sort that out, a newer / custom OpenSSL version is probably required.

Some useful information may be found here:
- https://apple.stackexchange.com/questions/126830/how-to-upgrade-openssl-in-os-x
- https://unix.stackexchange.com/questions/346864/how-to-link-openssl-library-in-macos-using-gcc

**Comment by astefanutti** [comment]
If the above is correct, I would have expected the OpenSSL library to be statically linked. That's an additional point to check.

It seems it will change in PhantomJS 2.5, see ariya/phantomjs#14320.

**Comment by lowescott** [comment]
FWIW, the current "official" PhantomJS binary (2.1.1) does not produce the same libssl error on either macOS 10.11.6 or macOS 10.12.5. Of course, it doesn't work with Decktape, either.

**Comment by astefanutti** [comment]
That's good to know. Indeed, outputting the shared libraries used by the Decktape binary print `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib`:

```
otool -L bin/phantomjs 
bin/phantomjs:
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.7.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1500.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1348.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57740.1.18)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 888.1.2)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 252.0.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 57.1.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

While the 2.1.1 "official binary" does not (yet does not print dependency on system installed OpenSSL???):

```
otool -L phantomjs-2.1.1-macosx
phantomjs-2.1.1-macosx:
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1256.1.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.6.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1256.14.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57337.20.43)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 802.20.7)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1404.32.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 216.4.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 55.1.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

It seems it's been introduced with ariya/phantomjs@6991949e74e3115472754198ec7e1c6793f1fbdd.

At a short term workaround, I wonder whether you could try creating a symboling link and give it a try:

```
ln -s /usr/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```

**Comment by lowescott** [comment]
@astefanutti So, I actually tried that. If you link to the `libssl.dylib` file in `/usr/lib`, you're getting version 0.9.8 and PhantomJS complains with a version error (indicating that it requires version 1.0.0 or later). On my system, I have an application installed that bundles `libssl1.0.0.dylib`, so I tried linking to that. Then it complains about needing `libcrypto1.0.0.dylib`. The application also bundles that, so I added a link for `libcrypto1.0.0.dylib`. At this point PhantomJS complains about not being able to load `/usr/lib/libcrypto1.0.0.dylib`. Due to SIP, it's impossible (without disabling SIP) to do anything to `/usr/lib`, so you're just stuck.

**Comment by astefanutti** [comment]
Ah that's what I feared 😞. I still wonder how the 2.1.1 binary SSL support has been built and why it hasn't statically linked OpenSSL installed via Homebrew on my machine...

From the 2.1.1 build script, my understanding is that OpenSSL should come from Homebrew or MacPorts to use a newer version compared to the old system installed one, but should be statically linked:
https://github.com/ariya/phantomjs/blob/d9cda3dcd26b0e463533c5cc96e39c0f39fc32c1/build.py#L216-L230

It seems there can be some issues with statically linking OpenSSL:
- https://stackoverflow.com/questions/20843180/is-there-any-way-to-building-static-qt-with-static-openssl
- https://forum.qt.io/topic/55853/openssl-and-mac-os-x

That being said, it seems that has been changed in PhantomJS 2.5 so it may be easier to wait until Decktape rebases to that newer version of PhantomJS as this is the plan.

**Comment by astefanutti** [comment]
DeckTape 2.x now uses Puppeteer / headless Chrome, which somehow should fix that issue.
